/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:30 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableSet, CADisplayLink;

@interface _SBClientSideAnimationEngine : NSObject {

	NSMutableSet* _animations;
	CADisplayLink* _displayLink;
	NSMutableSet* _finishedAnimations;

}
+(id)sharedEngine;
-(void)_ensureDisplayLink;
-(void)updateAnimation:(id)arg1 ;
-(BOOL)isRunningAnimation:(id)arg1 ;
-(id)init;
-(void)stopAnimation:(id)arg1 ;
-(void)startAnimation:(id)arg1 ;
-(void)_tearDownDisplayLink;
-(void)_onDisplayLink:(id)arg1 ;
-(void)_updateDisplayLink;
@end

