/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:30 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/_SBScreenshotProvider.h>

@class UIScreen, SBScreenFlash, NSString;

@interface _SBDefaultScreenshotProvider : NSObject <_SBScreenshotProvider> {

	UIScreen* _screen;
	SBScreenFlash* _flasher;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) UIScreen * screen;                    //@synthesize screen=_screen - In the implementation block
@property (nonatomic,readonly) SBScreenFlash * flasher;              //@synthesize flasher=_flasher - In the implementation block
-(id)captureScreenshot;
-(SBScreenFlash *)flasher;
-(UIScreen *)screen;
-(id)initWithScreen:(id)arg1 ;
@end

