/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:32 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBLockScreenBatteryChargingView.h>

@class UIView, _UIBackdropView, SBLockScreenBatteryFillView, _UILegibilityLabel, UIImageView;

@interface _SBLockScreenDoubleBatteryChargingView : SBLockScreenBatteryChargingView {

	UIView* _batteryContainerView;
	UIView* _internalBatteryContainerView;
	UIView* _externalBatteryContainerView;
	_UIBackdropView* _internalBatteryBlurView;
	_UIBackdropView* _externalBatteryBlurView;
	SBLockScreenBatteryFillView* _internalBatteryFillView;
	SBLockScreenBatteryFillView* _externalBatteryFillView;
	_UILegibilityLabel* _internalChargePercentLabel;
	_UILegibilityLabel* _externalChargePercentLabel;
	_UILegibilityLabel* _internalChargingNameLabel;
	_UILegibilityLabel* _externalChargingNameLabel;
	UIImageView* _internalChargingIndicator;
	UIImageView* _externalChargingIndicator;

}

@property (nonatomic,retain) _UILegibilityLabel * internalChargePercentLabel;              //@synthesize internalChargePercentLabel=_internalChargePercentLabel - In the implementation block
@property (nonatomic,retain) _UILegibilityLabel * externalChargePercentLabel;              //@synthesize externalChargePercentLabel=_externalChargePercentLabel - In the implementation block
-(void)setPrimaryChargePercentage:(long long)arg1 isCharging:(BOOL)arg2 detailed:(BOOL)arg3 ;
-(void)setSecondaryChargePercentage:(long long)arg1 isCharging:(BOOL)arg2 deviceName:(id)arg3 ;
-(BOOL)batteryVisible;
-(void)setBatteryVisible:(BOOL)arg1 ;
-(double)desiredVisibilityDuration;
-(id)_chargePercentFont;
-(double)_spaceBetweenBatteryImages;
-(void)setInternalChargePercentLabel:(_UILegibilityLabel *)arg1 ;
-(void)setExternalChargePercentLabel:(_UILegibilityLabel *)arg1 ;
-(double)_batteryTopPadding;
-(double)_chargingBoltTopOffset;
-(double)_deviceNameBaselineOffset;
-(double)_deviceChargeBaselineOffset;
-(_UILegibilityLabel *)internalChargePercentLabel;
-(_UILegibilityLabel *)externalChargePercentLabel;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setLegibilitySettings:(id)arg1 ;
@end

