/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:34 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBApplicationLibraryObserver <NSObject>
@optional
-(void)applicationLibrary:(id)arg1 didAddPlaceholders:(id)arg2;
-(void)applicationLibrary:(id)arg1 didCancelPlaceholders:(id)arg2;
-(void)applicationLibrary:(id)arg1 didAddApplications:(id)arg2;
-(void)applicationLibrary:(id)arg1 didReplaceApplications:(id)arg2 withApplications:(id)arg3;
-(void)applicationLibrary:(id)arg1 didRemoveApplications:(id)arg2;
-(void)applicationLibrary:(id)arg1 didDemoteApplications:(id)arg2;
-(void)applicationLibrary:(id)arg1 networkUsageDidChange:(BOOL)arg2;

@end

