/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:28 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SBAlertManagerDelegate <NSObject>
@optional
-(BOOL)alertManager:(id)arg1 shouldDeactivateDismissedAlert:(id)arg2;
-(id)alertManager:(id)arg1 newAlertWindowForScene:(id)arg2;
-(BOOL)alertManager:(id)arg1 defaultShouldAutorotateForAlert:(id)arg2;
-(long long)alertManager:(id)arg1 defaultInterfaceOrientationForPresentationOfAlert:(id)arg2;
-(unsigned long long)alertManager:(id)arg1 defaultSupportedInterfaceOrientationsForAlert:(id)arg2;

@required
-(CGRect*)sceneFrameForAlerts:(id)arg1;
-(double)sceneLevelForAlerts;

@end

