/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:28 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIView.h>

@class SBAlert;

@interface SBAlertView : UIView {

	SBAlert* _alert;
	unsigned _shouldAnimateIn : 1;

}
-(void)layoutForInterfaceOrientation:(long long)arg1 ;
-(void)alertDisplayWillBecomeVisible;
-(void)alertDisplayBecameVisible;
-(BOOL)isReadyToBeRemovedFromView;
-(BOOL)isAnimatingOut;
-(BOOL)shouldAddClippingViewDuringRotation;
-(void)alertWindowViewControllerResizedFromContentFrame:(CGRect)arg1 toContentFrame:(CGRect)arg2 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2 ;
-(void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2 ;
-(void)didRotateFromInterfaceOrientation:(long long)arg1 ;
-(void)dismiss;
-(BOOL)shouldAnimateIn;
-(void)setShouldAnimateIn:(BOOL)arg1 ;
-(id)alert;
-(void)setAlert:(id)arg1 ;
@end

