/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:32 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/_UISettings.h>

@interface SBAnimationCurveSettings : _UISettings {

	unsigned long long _curve;
	CGPoint _controlPoint1;
	CGPoint _controlPoint2;

}

@property (assign,nonatomic) unsigned long long curve;              //@synthesize curve=_curve - In the implementation block
@property (assign,nonatomic) CGPoint controlPoint1;                 //@synthesize controlPoint1=_controlPoint1 - In the implementation block
@property (assign,nonatomic) CGPoint controlPoint2;                 //@synthesize controlPoint2=_controlPoint2 - In the implementation block
+(id)_rowsRelativeToKeyPath:(id)arg1 ;
+(id)settingsControllerModule;
-(void)setControlPoint1:(CGPoint)arg1 ;
-(void)setControlPoint2:(CGPoint)arg1 ;
-(void)setCurve:(unsigned long long)arg1 ;
-(void)setDefaultValues;
-(unsigned long long)curve;
-(void)_invalidate;
-(CGPoint)controlPoint1;
-(CGPoint)controlPoint2;
@end

