/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:32 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIView.h>

@protocol SBApplicationShortcutMenuContentViewDelegate;
@class SBApplicationShortcutMenuBackgroundView, UIView, UIImageView, NSMutableArray, UILongPressGestureRecognizer, _UIAssetManager;

@interface SBApplicationShortcutMenuContentView : UIView {

	SBApplicationShortcutMenuBackgroundView* _backgroundView;
	UIView* _rowAndMaskContainer;
	UIView* _rowContainer;
	UIView* _dividerContainer;
	UIImageView* _maskView;
	NSMutableArray* _itemViews;
	NSMutableArray* _dividers;
	UILongPressGestureRecognizer* _pressGestureRecognizer;
	id<SBApplicationShortcutMenuContentViewDelegate> _delegate;
	long long _orientation;
	double _cornerRadius;
	unsigned long long _maskPresentSlideDirection;
	_UIAssetManager* _assetManager;
	CGRect _initialFrame;
	CGRect _containerBounds;
	CGRect _maxConcentricFrame;
	CGRect _maxMenuFrame;
	CGRect _dismissStartingFrame;
	long long _menuPosition;

}

@property (nonatomic,readonly) long long menuPosition;                                                      //@synthesize menuPosition=_menuPosition - In the implementation block
@property (assign,nonatomic,__weak) id<SBApplicationShortcutMenuContentViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) double cornerRadius;                                                           //@synthesize cornerRadius=_cornerRadius - In the implementation block
@property (nonatomic,retain) _UIAssetManager * assetManager;                                                //@synthesize assetManager=_assetManager - In the implementation block
+(double)defaultCornerRadius;
-(long long)menuPosition;
-(long long)_preferredMenuPositionWithContainerBounds:(CGRect)arg1 menuItemCount:(long long)arg2 ;
-(void)_configureForMenuPosition:(long long)arg1 menuItemCount:(long long)arg2 ;
-(void)_populateRowsWithShortcutItems:(id)arg1 application:(id)arg2 ;
-(double)_rowHeight;
-(double)_menuWidth;
-(void)setAssetManager:(_UIAssetManager *)arg1 ;
-(CGRect)_maxMenuFrameForIconFrame:(CGRect)arg1 menuPosition:(long long)arg2 menuItemCount:(unsigned long long)arg3 ;
-(void)_enumerateAllowedMenuPositionsInPreferredOrderUsingBlock:(/*^block*/id)arg1 ;
-(CGRect)_maxMenuFrameInsideContainerBounds:(CGRect)arg1 iconFrame:(CGRect)arg2 menuPosition:(long long)arg3 menuItemCount:(unsigned long long)arg4 ;
-(void)_prepareForDismiss;
-(void)_peekForFraction:(double)arg1 ;
-(void)_presentForFraction:(double)arg1 ;
-(void)_dismissForFraction:(double)arg1 ;
-(void)_updateMaskForFraction:(double)arg1 exponentialFraction:(double)arg2 menuContentFrame:(CGRect)arg3 ;
-(void)_updateRowContainerTransformForFraction:(double)arg1 menuContentFrame:(CGRect)arg2 ;
-(void)updateSelectionFromPressGestureRecognizer:(id)arg1 ;
-(double)_iconMenuMargin;
-(id)initWithInitialFrame:(CGRect)arg1 containerBounds:(CGRect)arg2 orientation:(long long)arg3 shortcutItems:(id)arg4 application:(id)arg5 ;
-(void)prepareForTransitionType:(unsigned long long)arg1 ;
-(void)updateFraction:(double)arg1 forTransitionType:(unsigned long long)arg2 ;
-(double)peekScaleAmount;
-(void)setDelegate:(id<SBApplicationShortcutMenuContentViewDelegate>)arg1 ;
-(void)layoutSubviews;
-(id<SBApplicationShortcutMenuContentViewDelegate>)delegate;
-(void)setCornerRadius:(double)arg1 ;
-(BOOL)isEmpty;
-(double)cornerRadius;
-(_UIAssetManager *)assetManager;
-(void)_handlePress:(id)arg1 ;
@end

