/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:31 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <FrontBoard/FBTransaction.h>

@class NSSet, NSMutableSet;

@interface SBAppRepairTransaction : FBTransaction {

	NSSet* _appInfos;
	NSMutableSet* _repairRequests;

}

@property (nonatomic,copy,readonly) NSSet * appInfos;              //@synthesize appInfos=_appInfos - In the implementation block
-(void)_startAppRepairs;
-(void)_completeRequest:(id)arg1 success:(BOOL)arg2 error:(id)arg3 ;
-(id)initWithApplicationInfos:(id)arg1 ;
-(NSSet *)appInfos;
-(void)_evaluateCompletion;
-(void)_didComplete;
-(BOOL)_canBeInterrupted;
-(void)_begin;
@end

