/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:33 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIView.h>
#import <SpringBoard/SBIconViewDelegate.h>
#import <SpringBoard/SBApplicationShortcutMenuContentViewDelegate.h>
#import <UIKit/UIInteractionProgressObserver.h>
#import <UIKit/UIGestureRecognizerDelegate.h>

@protocol SBApplicationShortcutMenuDelegate;
@class SBApplication, UIInteractionProgress, SBFParallaxSettings, UIView, _UIBackdropViewSettings, _UIBackdropView, SBIconView, SBApplicationShortcutMenuContentView, UITapGestureRecognizer, SBClientSideAnimation, NSMutableArray, SBAppStatusBarSettingsAssertion, NSString;

@interface SBApplicationShortcutMenu : UIView <SBIconViewDelegate, SBApplicationShortcutMenuContentViewDelegate, UIInteractionProgressObserver, UIGestureRecognizerDelegate> {

	SBApplication* _application;
	UIInteractionProgress* _interactionProgress;
	id<SBApplicationShortcutMenuDelegate> _applicationShortcutMenuDelegate;
	SBFParallaxSettings* _parallaxSettings;
	UIView* _transformedContainerView;
	long long _orientation;
	UIView* _backgroundContainerView;
	UIView* _foregroundContainerView;
	_UIBackdropViewSettings* _blurSettings;
	_UIBackdropView* _blurView;
	UIView* _proxyIconViewWrapper;
	SBIconView* _proxyIconView;
	SBApplicationShortcutMenuContentView* _contentView;
	unsigned long long _presentState;
	double _contentTransitionFraction;
	double _blurAndScaleTransitionFraction;
	double _iconScaleFactor;
	UITapGestureRecognizer* _dismissGestureRecognizer;
	SBClientSideAnimation* _presentAnimation;
	SBClientSideAnimation* _dismissAnimation;
	SBClientSideAnimation* _finishPeekingAnimation;
	NSMutableArray* _dismissCompletionBlocks;
	long long _editingForceScore;
	double _lastForceUpdateTime;
	double _presentationStartTime;
	double _lastForceUpdateFraction;
	BOOL _interactionProgressEnded;
	SBAppStatusBarSettingsAssertion* _hideStatusBarAssertion;
	SBIconView* _iconView;

}

@property (nonatomic,retain) SBApplication * application;                                                               //@synthesize application=_application - In the implementation block
@property (assign,nonatomic,__weak) SBIconView * iconView;                                                              //@synthesize iconView=_iconView - In the implementation block
@property (nonatomic,readonly) UIInteractionProgress * interactionProgress;                                             //@synthesize interactionProgress=_interactionProgress - In the implementation block
@property (nonatomic,readonly) BOOL isPresented; 
@property (assign,nonatomic,__weak) id<SBApplicationShortcutMenuDelegate> applicationShortcutMenuDelegate;              //@synthesize applicationShortcutMenuDelegate=_applicationShortcutMenuDelegate - In the implementation block
@property (nonatomic,retain) SBFParallaxSettings * parallaxSettings;                                                    //@synthesize parallaxSettings=_parallaxSettings - In the implementation block
@property (nonatomic,retain) UIView * transformedContainerView;                                                         //@synthesize transformedContainerView=_transformedContainerView - In the implementation block
@property (assign,nonatomic) unsigned long long presentState;                                                           //@synthesize presentState=_presentState - In the implementation block
@property (nonatomic,retain) SBClientSideAnimation * presentAnimation;                                                  //@synthesize presentAnimation=_presentAnimation - In the implementation block
@property (nonatomic,retain) SBClientSideAnimation * dismissAnimation;                                                  //@synthesize dismissAnimation=_dismissAnimation - In the implementation block
@property (nonatomic,retain) SBClientSideAnimation * finishPeekingAnimation;                                            //@synthesize finishPeekingAnimation=_finishPeekingAnimation - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)prepareForPotentialPresentationWithReason:(id)arg1 ;
+(void)cancelPrepareForPotentialPresentationWithReason:(id)arg1 ;
+(id)_potentialPresentationReasons;
-(SBFParallaxSettings *)parallaxSettings;
-(void)iconHandleLongPress:(id)arg1 ;
-(void)updateFromPressGestureRecognizer:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 application:(id)arg2 iconView:(id)arg3 interactionProgress:(id)arg4 orientation:(long long)arg5 ;
-(void)setApplicationShortcutMenuDelegate:(id<SBApplicationShortcutMenuDelegate>)arg1 ;
-(void)setParallaxSettings:(SBFParallaxSettings *)arg1 ;
-(void)setTransformedContainerView:(UIView *)arg1 ;
-(void)iconTapped:(id)arg1 ;
-(void)iconTouchBegan:(id)arg1 ;
-(void)icon:(id)arg1 touchMoved:(id)arg2 ;
-(void)icon:(id)arg1 touchEnded:(BOOL)arg2 ;
-(BOOL)iconShouldAllowTap:(id)arg1 ;
-(BOOL)icon:(id)arg1 canReceiveGrabbedIcon:(id)arg2 ;
-(void)iconCloseBoxTapped:(id)arg1 ;
-(BOOL)iconViewDisplaysBadges:(id)arg1 ;
-(BOOL)iconViewDisplaysCloseBox:(id)arg1 ;
-(void)_handleDismissGesture:(id)arg1 ;
-(BOOL)menuContentView:(id)arg1 canActivateShortcutItem:(id)arg2 ;
-(void)menuContentView:(id)arg1 activateShortcutItem:(id)arg2 index:(long long)arg3 ;
-(id)_shortcutItemsToDisplay;
-(void)_peekWithContentFraction:(double)arg1 smoothedBlurFraction:(double)arg2 ;
-(void)_dismissAnimated:(BOOL)arg1 finishPeeking:(BOOL)arg2 ignorePresentState:(BOOL)arg3 completionHandler:(/*^block*/id)arg4 ;
-(void)setPresentState:(unsigned long long)arg1 ;
-(void)_updateBackgroundForBlurFraction:(double)arg1 ;
-(void)_applyIconScaleTransformWithIconFactor:(double)arg1 contentFactor:(double)arg2 ;
-(void)setPresentAnimation:(SBClientSideAnimation *)arg1 ;
-(id<SBApplicationShortcutMenuDelegate>)applicationShortcutMenuDelegate;
-(void)_finishPeekingWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)setDismissAnimation:(SBClientSideAnimation *)arg1 ;
-(void)setFinishPeekingAnimation:(SBClientSideAnimation *)arg1 ;
-(void)_updateEditingScoreWithForceVelocity:(double)arg1 ;
-(void)_scheduleUpdateEditingScoreAfterTimeout;
-(void)_cancelUpdateEditingScoreTimer;
-(void)_updateEditingScoreAfterTimeout;
-(BOOL)_canDisplayShortcutItem:(id)arg1 ;
-(unsigned long long)presentState;
-(SBClientSideAnimation *)presentAnimation;
-(SBClientSideAnimation *)dismissAnimation;
-(SBClientSideAnimation *)finishPeekingAnimation;
-(void)icon:(id)arg1 openFolder:(id)arg2 animated:(BOOL)arg3 ;
-(void)dealloc;
-(void)layoutSubviews;
-(NSString *)description;
-(BOOL)gestureRecognizerShouldBegin:(id)arg1 ;
-(void)interactionProgressDidUpdate:(id)arg1 ;
-(void)interactionProgress:(id)arg1 didEnd:(BOOL)arg2 ;
-(UIView *)transformedContainerView;
-(UIInteractionProgress *)interactionProgress;
-(BOOL)isPresented;
-(SBIconView *)iconView;
-(void)setIconView:(SBIconView *)arg1 ;
-(void)dismissAnimated:(BOOL)arg1 completionHandler:(/*^block*/id)arg2 ;
-(SBApplication *)application;
-(void)setApplication:(SBApplication *)arg1 ;
-(void)presentAnimated:(BOOL)arg1 ;
-(void)_setupViews;
@end

