/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:34 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIScrollView.h>

@class SBMainAppSwitcherPageView;

@interface SBAppSwitcherItemScrollView : UIScrollView {

	SBMainAppSwitcherPageView* _item;
	long long _layoutOrientation;

}

@property (nonatomic,retain) SBMainAppSwitcherPageView * item;              //@synthesize item=_item - In the implementation block
@property (assign,nonatomic) long long layoutOrientation;                   //@synthesize layoutOrientation=_layoutOrientation - In the implementation block
-(void)_disableScrolling;
-(void)_enableScrolling;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(SBMainAppSwitcherPageView *)item;
-(long long)layoutOrientation;
-(void)setLayoutOrientation:(long long)arg1 ;
-(void)setItem:(SBMainAppSwitcherPageView *)arg1 ;
@end

