/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:31 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBPanSystemGestureRecognizer.h>

@interface SBBannerDismissSystemGestureRecognizer : SBPanSystemGestureRecognizer

@property (assign,nonatomic,__weak) id<SBBannerDismissSystemGestureRecognizerDelegate> delegate; 
-(id)initWithTarget:(id)arg1 action:(SEL)arg2 ;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2 ;
@end

