/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:32 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBFileLogger.h>

@interface SBBannerLogger : SBFileLogger
-(id)name;
-(int)level;
-(void)_setEnabled:(BOOL)arg1 ;
-(void)_setLevel:(int)arg1 ;
-(id)logPreferenceName;
-(id)logPrefixForCategory:(id)arg1 destination:(unsigned long long)arg2 ;
@end

