/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:29 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBLeafIcon.h>

@class SBBookmark, UIWebClip, NSURL;

@interface SBBookmarkIcon : SBLeafIcon {

	SBBookmark* _bookmark;

}

@property (nonatomic,readonly) SBBookmark * bookmark;              //@synthesize bookmark=_bookmark - In the implementation block
@property (nonatomic,readonly) UIWebClip * webClip; 
@property (nonatomic,readonly) NSURL * launchURL; 
-(id)folderTitleOptions;
-(id)folderFallbackTitle;
-(id)matchedWebApplication;
-(BOOL)isBookmarkIcon;
-(id)initWithBookmark:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSURL *)launchURL;
-(SBBookmark *)bookmark;
-(UIWebClip *)webClip;
@end

