/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:33 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBCenterIconZoomAnimator.h>

@class UIView, SBCenterAppZoomSettings;

@interface SBCenterAppIconZoomAnimator : SBCenterIconZoomAnimator {

	UIView* _appView;
	CGRect _destinationFrame;
	double _distantScale;

}

@property (nonatomic,retain) SBCenterAppZoomSettings * settings; 
@property (assign) double distantScale;                                       //@synthesize distantScale=_distantScale - In the implementation block
-(void)_cleanupAnimation;
-(void)_prepareAnimation;
-(void)_setAnimationFraction:(double)arg1 ;
-(unsigned long long)_numberOfSignificantAnimations;
-(void)_animateToFraction:(double)arg1 afterDelay:(double)arg2 withSharedCompletion:(/*^block*/id)arg3 ;
-(id)initWithFolderController:(id)arg1 appView:(id)arg2 ;
-(void)setDistantScale:(double)arg1 ;
-(double)_iconZoomDelay;
-(void)_delayedForRotation;
-(void)_zoomAppForZoomFraction:(double)arg1 ;
-(void)_fadeAppForZoomFraction:(double)arg1 ;
-(double)_appZoomDelay;
-(double)distantScale;
-(CGPoint)cameraPosition;
@end

