/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:33 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBSnippetSectionInfo.h>

@class UIImage;

@interface SBChildSectionInfo : SBSnippetSectionInfo {

	UIImage* _settingsIcon;

}
+(id)sectionInfoWithDataSource:(id)arg1 ;
-(id)settingsIcon;
-(void)setSettingsIcon:(id)arg1 ;
@end

