/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:30 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIViewController.h>
#import <SpringBoard/SBControlCenterObserver.h>

@protocol SBControlCenterSectionViewControllerDelegate;
@class NSString;

@interface SBControlCenterSectionViewController : UIViewController <SBControlCenterObserver> {

	id<SBControlCenterSectionViewControllerDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<SBControlCenterSectionViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy,readonly) NSString * sectionIdentifier; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(Class)viewClass;
-(void)controlCenterWillPresent;
-(void)controlCenterDidDismiss;
-(CGSize)contentSizeForOrientation:(long long)arg1 ;
-(BOOL)enabledForOrientation:(long long)arg1 ;
-(void)controlCenterWillBeginTransition;
-(void)controlCenterDidFinishTransition;
-(void)noteSettingsDidUpdate:(id)arg1 ;
-(void)setDelegate:(id<SBControlCenterSectionViewControllerDelegate>)arg1 ;
-(id<SBControlCenterSectionViewControllerDelegate>)delegate;
-(id)view;
-(void)loadView;
-(NSString *)sectionIdentifier;
@end

