/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:30 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <SpringBoard/SpringBoard-Structs.h>
@interface SBConferenceManager : NSObject {

	BOOL _hasFaceTimeCapability;
	MGNotificationTokenStructRef _faceTimeCapabilityUpdateToken;

}
+(id)sharedInstance;
+(void)initialize;
-(void)endFaceTime;
-(BOOL)inFaceTime;
-(BOOL)faceTimeInvitationExists;
-(BOOL)hasFaceTimeCapability;
-(BOOL)canStartFaceTime;
-(BOOL)activeFaceTimeCallExists;
-(void)_faceTimeStateChanged:(id)arg1 ;
-(void)_faceTimeCapabilityChanged:(id)arg1 ;
-(id)incomingFaceTimeCall;
-(id)activeFaceTimeCall;
-(id)currentFaceTimeCall;
-(id)_faceTimeApp;
-(BOOL)faceTimeIsAvailable;
-(void)dealloc;
-(id)init;
@end

