/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:31 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIViewController.h>
#import <SpringBoard/SBControlCenterViewControllerDelegate.h>
#import <UIKit/UIGestureRecognizerDelegate.h>
#import <SpringBoard/SBSystemGestureRecognizerDelegate.h>
#import <SpringBoard/SBCoordinatedPresenting.h>

@class SBWindow, SBControlCenterRootView, SBControlCenterViewController, UIImageView, UIView, _UIBackdropView, SBChevronView, SBScreenEdgePanGestureRecognizer, FBUIApplicationSceneDeactivationAssertion, FBDisplayLayoutElement, NSMutableSet, NSHashTable, _UIDynamicValueAnimation, UIDynamicAnimator, NSString, NSSet;

@interface SBControlCenterController : UIViewController <SBControlCenterViewControllerDelegate, UIGestureRecognizerDelegate, SBSystemGestureRecognizerDelegate, SBCoordinatedPresenting> {

	SBWindow* _window;
	SBControlCenterRootView* _rootView;
	SBControlCenterViewController* _viewController;
	UIImageView* _coveredContentSnapshot;
	UIView* _fullScreenGrabberContainer;
	_UIBackdropView* _fullScreenGrabberBackdrop;
	SBChevronView* _fullScreenChevron;
	SBScreenEdgePanGestureRecognizer* _controlCenterGestureRecognizer;
	double _controlCenterGestureStartTime;
	FBUIApplicationSceneDeactivationAssertion* _resignActiveAssertion;
	FBDisplayLayoutElement* _displayLayoutElement;
	NSMutableSet* _preventDismissalOnLockReasons;
	BOOL _uiLocked;
	NSHashTable* _observers;
	long long _orientation;
	BOOL _animatingInitialPresentation;
	BOOL _gotFirstBackdropUpdate;
	BOOL _completingTransitionOpen;
	_UIDynamicValueAnimation* _bounceAnimation;
	UIDynamicAnimator* _animator;
	unsigned long long _animatorStopCount;
	CGRect _animatorStopFrame;
	BOOL _presented;
	BOOL _inGrabberOnlyMode;
	BOOL _transitioning;
	BOOL _fullyRevealed;
	double _backgroundBrightness;
	double _ambiguousActivationMargin;

}

@property (assign,getter=isPresented,nonatomic) BOOL presented;                                               //@synthesize presented=_presented - In the implementation block
@property (assign,nonatomic) BOOL inGrabberOnlyMode;                                                          //@synthesize inGrabberOnlyMode=_inGrabberOnlyMode - In the implementation block
@property (assign,getter=isUILocked,nonatomic) BOOL UILocked;                                                 //@synthesize uiLocked=_uiLocked - In the implementation block
@property (assign,getter=isTransitioning,nonatomic) BOOL transitioning;                                       //@synthesize transitioning=_transitioning - In the implementation block
@property (assign,getter=isFullyRevealed,nonatomic) BOOL fullyRevealed;                                       //@synthesize fullyRevealed=_fullyRevealed - In the implementation block
@property (assign,nonatomic) double backgroundBrightness;                                                     //@synthesize backgroundBrightness=_backgroundBrightness - In the implementation block
@property (assign,getter=_ambiguousActivationMargin,nonatomic) double ambiguousActivationMargin;              //@synthesize ambiguousActivationMargin=_ambiguousActivationMargin - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) long long coordinatedPresentingControllerIdentifier; 
@property (nonatomic,readonly) double hintDisplacement; 
@property (nonatomic,readonly) unsigned long long hintEdge; 
@property (assign,nonatomic) id<SBPresentingDelegate> presentingDelegate; 
@property (nonatomic,readonly) NSSet * gestures; 
@property (nonatomic,readonly) NSSet * conflictingGestures; 
@property (nonatomic,readonly) NSSet * tapExcludedViews; 
+(void)notifyControlCenterControl:(id)arg1 didActivate:(BOOL)arg2 ;
+(double)transitionAnimationDuration;
+(id)_sharedInstanceCreatingIfNeeded:(BOOL)arg1 ;
+(id)sharedInstance;
+(id)sharedInstanceIfExists;
-(BOOL)isUILocked;
-(void)updateTransitionWithTouchLocation:(CGPoint)arg1 velocity:(CGPoint)arg2 ;
-(void)endTransitionWithVelocity:(CGPoint)arg1 wasCancelled:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(void)beginPresentationWithTouchLocation:(CGPoint)arg1 presentationBegunHandler:(/*^block*/id)arg2 ;
-(BOOL)isGrabberVisible;
-(void)setAmbiguousActivationMargin:(double)arg1 forApp:(id)arg2 ;
-(id)viewForSystemGestureRecognizer:(id)arg1 ;
-(void)presentAnimated:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)_dismissOnLock;
-(BOOL)isPresentingControllerTransitioning;
-(void)abortAnimatedTransition;
-(long long)coordinatedPresentingControllerIdentifier;
-(double)hintDisplacement;
-(unsigned long long)hintEdge;
-(void)dismissAnimated:(BOOL)arg1 withAdditionalAnimations:(/*^block*/id)arg2 completion:(/*^block*/id)arg3 ;
-(void)_lockStateChangedNotification:(id)arg1 ;
-(void)_uiRelockedNotification:(id)arg1 ;
-(void)setUILocked:(BOOL)arg1 ;
-(void)_handleShowControlCenterGesture:(id)arg1 ;
-(void)_enumerateObservers:(/*^block*/id)arg1 ;
-(void)_updateCoveredContentSnapshot;
-(void)_clearCoveredContentSnapshot;
-(BOOL)inGrabberOnlyMode;
-(double)_ambiguousActivationMargin;
-(double)_yValueForOpen;
-(double)_yValueForClosed;
-(void)_updateRevealPercentage:(double)arg1 ;
-(void)_updateGrabberVisibility;
-(void)hideGrabberAnimated:(BOOL)arg1 ;
-(void)_showControlCenterGestureBeganWithGestureRecognizer:(id)arg1 ;
-(void)_showControlCenterGestureChangedWithGestureRecognizer:(id)arg1 ;
-(void)_showControlCenterGestureEndedWithGestureRecognizer:(id)arg1 ;
-(void)_showControlCenterGestureCancelled;
-(void)_showControlCenterGestureFailed;
-(BOOL)_shouldShowGrabberOnFirstSwipe;
-(void)showGrabberAnimated:(BOOL)arg1 ;
-(BOOL)_shouldUseControlCenterRevealConfirmation;
-(void)_beginSystemGesturePresentationWithGestureRecognizer:(id)arg1 ;
-(void)_setupViewForPresentation;
-(void)_updateTransitionWithTouchLocation:(CGPoint)arg1 velocity:(CGPoint)arg2 ;
-(void)_hideGrabberForSystemGesture;
-(void)_endPresentation;
-(void)_beginTransitionWithTouchLocation:(CGPoint)arg1 ;
-(BOOL)isAvailableWhileLocked;
-(BOOL)_allowShowTransitionSystemGesture;
-(id)_controlCenterWindow;
-(void)setPresented:(BOOL)arg1 ;
-(void)_revealSlidingViewToHeight:(double)arg1 ;
-(void)_teardownWindowAfterPresentation;
-(void)_cleanupAnimator;
-(void)setInGrabberOnlyMode:(BOOL)arg1 ;
-(void)_beginPresentation;
-(void)_doSetupBeforeBeginTransition;
-(double)_controlCenterHeightForTouchLocation:(CGPoint)arg1 ;
-(void)_setLockHUDHidden:(BOOL)arg1 ;
-(void)_finishPresenting:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(double)_verticalPercentageMovedOnScreenForY:(double)arg1 stopY:(double)arg2 ;
-(id)_newDynamicAnimationForShow:(BOOL)arg1 currentValue:(double)arg2 velocity:(double)arg3 unitSize:(double)arg4 ;
-(BOOL)isFullyRevealed;
-(void)_dismissWithDuration:(double)arg1 additionalAnimations:(/*^block*/id)arg2 completion:(/*^block*/id)arg3 ;
-(void)setFullyRevealed:(BOOL)arg1 ;
-(void)_resetControlAlpha;
-(void)hideGrabberAnimated:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)_updateShouldShowGrabberOnFirstSwipe;
-(BOOL)allowShowTransitionSystemGesture;
-(void)_endTransitionWithVelocity:(CGPoint)arg1 completion:(/*^block*/id)arg2 ;
-(void)setBackgroundBrightness:(double)arg1 ;
-(void)_updateControlAlphaForBrightness:(double)arg1 ;
-(void)controlCenterViewControllerWantsDismissal:(id)arg1 ;
-(BOOL)controlCenterViewController:(id)arg1 canHandleGestureRecognizer:(id)arg2 ;
-(void)controlCenterViewController:(id)arg1 handleTap:(id)arg2 ;
-(void)controlCenterViewController:(id)arg1 handlePan:(id)arg2 ;
-(void)controlCenterViewController:(id)arg1 backdropViewDidUpdate:(id)arg2 ;
-(void)preventDismissalOnLock:(BOOL)arg1 forReason:(id)arg2 ;
-(BOOL)allowHideTransition;
-(void)beginTransitionWithTouchLocation:(CGPoint)arg1 ;
-(void)endTransitionWithVelocity:(CGPoint)arg1 completion:(/*^block*/id)arg2 ;
-(double)backgroundBrightness;
-(void)setAmbiguousActivationMargin:(double)arg1 ;
-(void)dealloc;
-(id)init;
-(BOOL)gestureRecognizerShouldBegin:(id)arg1 ;
-(void)addObserver:(id)arg1 ;
-(BOOL)shouldAutorotate;
-(void)loadView;
-(void)removeObserver:(id)arg1 ;
-(BOOL)wantsFullScreenLayout;
-(BOOL)isTransitioning;
-(BOOL)shouldAutomaticallyForwardRotationMethods;
-(BOOL)shouldAutomaticallyForwardAppearanceMethods;
-(BOOL)isVisible;
-(void)dismissAnimated:(BOOL)arg1 ;
-(BOOL)isPresented;
-(void)setTransitioning:(BOOL)arg1 ;
-(BOOL)handleMenuButtonTap;
-(void)presentAnimated:(BOOL)arg1 ;
-(void)dismissAnimated:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)_cancelTransition;
-(void)_presentWithDuration:(double)arg1 completion:(/*^block*/id)arg2 ;
-(BOOL)allowShowTransition;
@end

