/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:31 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SBControlCenterViewControllerDelegate <NSObject>
@required
-(void)controlCenterViewControllerWantsDismissal:(id)arg1;
-(BOOL)controlCenterViewController:(id)arg1 canHandleGestureRecognizer:(id)arg2;
-(void)controlCenterViewController:(id)arg1 handleTap:(id)arg2;
-(void)controlCenterViewController:(id)arg1 handlePan:(id)arg2;
-(void)controlCenterViewController:(id)arg1 backdropViewDidUpdate:(id)arg2;

@end

