/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:33 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <BaseBoard/BSAbstractDefaultDomain.h>

@class NSArray;

@interface SBExternalOperatorDefaults : BSAbstractDefaultDomain

@property (nonatomic,readonly) NSArray * statusBarImageDictionaries; 
-(void)setStatusBarImageDictionaries:(NSArray *)arg1 ;
-(NSArray *)statusBarImageDictionaries;
-(void)synchronizeOperatorPreferences;
-(id)init;
-(void)_bindAndRegisterDefaults;
@end

