/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:31 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoardFoundation/SBAbstractDefaults.h>

@class SBExternalGlobalDefaults, SBExternalCarrierDefaults, SBExternalOperatorDefaults, SBExternalUIKitDefaults, SBExternalBluetoothDefaults, SBExternalDuetDefaults, SBExternalDemoDefaults, SBExternalSetupDefaults, SBExternalSettingsDefaults, SBExternalSMSDefaults, SBExternalPhoneDefaults, SBExternalWifiDefaults, SBExternalSoundsDefaults;

@interface SBExternalDefaults : SBAbstractDefaults {

	SBExternalGlobalDefaults* _lazy_globalDefaults;
	SBExternalCarrierDefaults* _lazy_carrierDefaults;
	SBExternalOperatorDefaults* _lazy_operatorDefaults;
	SBExternalUIKitDefaults* _lazy_uikitDefaults;
	SBExternalBluetoothDefaults* _lazy_bluetoothDefaults;
	SBExternalDuetDefaults* _lazy_duetDefaults;
	SBExternalDemoDefaults* _lazy_demoDefaults;
	SBExternalSetupDefaults* _lazy_setupDefaults;
	SBExternalSettingsDefaults* _lazy_settingsDefaults;
	SBExternalSMSDefaults* _lazy_smsDefaults;
	SBExternalPhoneDefaults* _lazy_phoneDefaults;
	SBExternalWifiDefaults* _lazy_networkDefaults;
	SBExternalSoundsDefaults* _lazy_soundDefaults;
	SBExternalGlobalDefaults* _lazyglobalDefaults;
	SBExternalCarrierDefaults* _lazycarrierDefaults;
	SBExternalOperatorDefaults* _lazyoperatorDefaults;
	SBExternalUIKitDefaults* _lazyuikitDefaults;
	SBExternalBluetoothDefaults* _lazybluetoothDefaults;
	SBExternalDuetDefaults* _lazyduetDefaults;
	SBExternalDemoDefaults* _lazydemoDefaults;
	SBExternalSetupDefaults* _lazysetupDefaults;
	SBExternalSettingsDefaults* _lazysettingsDefaults;
	SBExternalSMSDefaults* _lazysmsDefaults;
	SBExternalPhoneDefaults* _lazyphoneDefaults;
	SBExternalWifiDefaults* _lazynetworkDefaults;
	SBExternalSoundsDefaults* _lazysoundDefaults;

}

@property (nonatomic,retain,readonly) SBExternalGlobalDefaults * globalDefaults;                    //@synthesize lazyglobalDefaults=_lazyglobalDefaults - In the implementation block
@property (nonatomic,retain,readonly) SBExternalCarrierDefaults * carrierDefaults;                  //@synthesize lazycarrierDefaults=_lazycarrierDefaults - In the implementation block
@property (nonatomic,retain,readonly) SBExternalOperatorDefaults * operatorDefaults;                //@synthesize lazyoperatorDefaults=_lazyoperatorDefaults - In the implementation block
@property (nonatomic,retain,readonly) SBExternalUIKitDefaults * uikitDefaults;                      //@synthesize lazyuikitDefaults=_lazyuikitDefaults - In the implementation block
@property (nonatomic,retain,readonly) SBExternalBluetoothDefaults * bluetoothDefaults;              //@synthesize lazybluetoothDefaults=_lazybluetoothDefaults - In the implementation block
@property (nonatomic,retain,readonly) SBExternalDuetDefaults * duetDefaults;                        //@synthesize lazyduetDefaults=_lazyduetDefaults - In the implementation block
@property (nonatomic,retain,readonly) SBExternalDemoDefaults * demoDefaults;                        //@synthesize lazydemoDefaults=_lazydemoDefaults - In the implementation block
@property (nonatomic,retain,readonly) SBExternalSetupDefaults * setupDefaults;                      //@synthesize lazysetupDefaults=_lazysetupDefaults - In the implementation block
@property (nonatomic,retain,readonly) SBExternalSettingsDefaults * settingsDefaults;                //@synthesize lazysettingsDefaults=_lazysettingsDefaults - In the implementation block
@property (nonatomic,retain,readonly) SBExternalSMSDefaults * smsDefaults;                          //@synthesize lazysmsDefaults=_lazysmsDefaults - In the implementation block
@property (nonatomic,retain,readonly) SBExternalPhoneDefaults * phoneDefaults;                      //@synthesize lazyphoneDefaults=_lazyphoneDefaults - In the implementation block
@property (nonatomic,retain,readonly) SBExternalWifiDefaults * networkDefaults;                     //@synthesize lazynetworkDefaults=_lazynetworkDefaults - In the implementation block
@property (nonatomic,retain,readonly) SBExternalSoundsDefaults * soundDefaults;                     //@synthesize lazysoundDefaults=_lazysoundDefaults - In the implementation block
-(SBExternalGlobalDefaults *)globalDefaults;
-(SBExternalPhoneDefaults *)phoneDefaults;
-(SBExternalCarrierDefaults *)carrierDefaults;
-(SBExternalOperatorDefaults *)operatorDefaults;
-(SBExternalWifiDefaults *)networkDefaults;
-(SBExternalSMSDefaults *)smsDefaults;
-(SBExternalUIKitDefaults *)uikitDefaults;
-(SBExternalBluetoothDefaults *)bluetoothDefaults;
-(SBExternalDuetDefaults *)duetDefaults;
-(SBExternalSettingsDefaults *)settingsDefaults;
-(SBExternalDemoDefaults *)demoDefaults;
-(SBExternalSoundsDefaults *)soundDefaults;
-(SBExternalSetupDefaults *)setupDefaults;
@end

