/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:31 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SoftwareUpdateServices/SUDescriptor.h>

@interface SBFakeSUDescriptor : SUDescriptor
-(id)documentation;
-(BOOL)isDownloadable;
-(unsigned long long)downloadSize;
-(id)productVersion;
-(int)updateType;
-(id)humanReadableUpdateName;
-(unsigned long long)installationSize;
-(unsigned long long)preparationSize;
-(BOOL)isDownloadableOverCellular;
-(id)publisher;
-(id)productBuildVersion;
-(id)productSystemName;
@end

