/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:30 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SBFolderObserver <NSObject>
@required
-(void)folder:(id)arg1 didAddList:(id)arg2;
-(void)folder:(id)arg1 didRemoveLists:(id)arg2 atIndexes:(id)arg3;

@end

