/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:30 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBIconListView.h>

@interface SBFolderIconListView : SBIconListView
+(unsigned long long)iconColumnsForInterfaceOrientation:(long long)arg1 ;
+(unsigned long long)maxVisibleIconRowsInterfaceOrientation:(long long)arg1 ;
-(double)bottomIconInset;
-(double)sideIconInset;
-(double)topIconInset;
-(int)iconLocation;
@end

