/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:31 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/_UISettings.h>

@interface SBHomeButtonTimingSettings : _UISettings {

	double _tapDuration;
	double _delay;

}

@property (assign,nonatomic) double tapDuration;              //@synthesize tapDuration=_tapDuration - In the implementation block
@property (assign,nonatomic) double delay;                    //@synthesize delay=_delay - In the implementation block
+(id)createWithDuration:(double)arg1 delay:(double)arg2 ;
+(id)settingsControllerModule;
-(double)tapDuration;
-(void)setTapDuration:(double)arg1 ;
-(id)description;
-(double)delay;
-(void)setDelay:(double)arg1 ;
-(void)setDefaultValues;
-(id)displayName;
@end

