/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:30 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIView.h>

@class SBIcon, SBIconViewMap, SBIconView;

@interface SBIconOverlayDarkeningView : UIView {

	SBIcon* _icon;
	SBIconViewMap* _iconViewMap;
	SBIconView* _iconView;

}
-(id)initWithFrame:(CGRect)arg1 icon:(id)arg2 viewMap:(id)arg3 ;
-(void)layoutSubviews;
@end

