/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:30 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SBIconListModelObserver <NSObject>
@required
-(void)iconList:(id)arg1 didRemoveIcon:(id)arg2;
-(void)iconList:(id)arg1 didAddIcon:(id)arg2;
-(void)iconList:(id)arg1 didReplaceIcon:(id)arg2 withIcon:(id)arg3;

@end

