/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:30 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIView.h>

@protocol SBLayoutElementContainerViewDelegate;
@class SBLayoutElementAdornmentView, UIView, SBOrientationTransformWrapperView, UIGestureRecognizer, UISwipeGestureRecognizer;

@interface SBLayoutElementContainerView : UIView {

	SBLayoutElementAdornmentView* _adornmentView;
	UIView* _contentView;
	SBOrientationTransformWrapperView* _contentWrapperView;
	UIGestureRecognizer* _dismissTapRecognizer;
	UISwipeGestureRecognizer* _dismissSwipeRecognizer;
	id<SBLayoutElementContainerViewDelegate> _delegate;
	BOOL _transitioning;
	long long _orientation;
	BOOL _keyboardVisible;
	CGRect _keyboardFrame;
	BOOL _resizing;
	double _pinResizeGrabberHorizontalOffset;

}

@property (assign,nonatomic,__weak) id<SBLayoutElementContainerViewDelegate> delegate;                         //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) long long dimmingLevel; 
@property (assign,nonatomic) BOOL wantsPinResizeGrabber; 
@property (assign,nonatomic) long long orientation; 
@property (assign,nonatomic) long long sideSwitcherGrabberStyle; 
@property (assign,getter=isSideSwitcherGrabberPressed,nonatomic) BOOL sideSwitcherGrabberPressed; 
@property (assign,nonatomic) double pinResizeGrabberHorizontalOffset;                                          //@synthesize pinResizeGrabberHorizontalOffset=_pinResizeGrabberHorizontalOffset - In the implementation block
@property (nonatomic,retain) UIView * contentView; 
@property (assign,getter=isResizing,nonatomic) BOOL resizing;                                                  //@synthesize resizing=_resizing - In the implementation block
-(void)setWantsPinResizeGrabber:(BOOL)arg1 withPercent:(double)arg2 ;
-(void)setWantsPinResizeGrabber:(BOOL)arg1 ;
-(void)_handleDimmingViewGesture:(id)arg1 ;
-(void)_keyboardFrameWillChange:(id)arg1 ;
-(long long)dimmingLevel;
-(void)setDimmingLevel:(long long)arg1 ;
-(void)setDimmingLevel:(long long)arg1 withPercent:(double)arg2 ;
-(long long)sideSwitcherGrabberStyle;
-(void)setSideSwitcherGrabberStyle:(long long)arg1 ;
-(BOOL)isSideSwitcherGrabberPressed;
-(void)setSideSwitcherGrabberPressed:(BOOL)arg1 ;
-(void)setResizing:(BOOL)arg1 ;
-(void)updateVibrancyForPinResizeGrabberView;
-(BOOL)wantsPinResizeGrabber;
-(void)setPinResizeGrabberHorizontalOffset:(double)arg1 ;
-(CGRect)pinResizeGrabberFrame;
-(void)didEndTransition;
-(void)willBeginResize;
-(void)didEndResize;
-(void)setLayoutElementViewAlpha:(double)arg1 ;
-(unsigned long long)_supportedOrientations;
-(id)_contentWrapperView;
-(double)pinResizeGrabberHorizontalOffset;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setDelegate:(id<SBLayoutElementContainerViewDelegate>)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id<SBLayoutElementContainerViewDelegate>)delegate;
-(BOOL)_isTransitioning;
-(BOOL)gestureRecognizerShouldBegin:(id)arg1 ;
-(void)setOrientation:(long long)arg1 ;
-(long long)orientation;
-(BOOL)_shouldAnimatePropertyWithKey:(id)arg1 ;
-(UIView *)contentView;
-(void)setContentView:(UIView *)arg1 ;
-(void)prepareForReuse;
-(BOOL)isResizing;
-(void)willBeginTransition;
@end

