/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:32 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBLockScreenPluginTransition.h>

@class SBLockOverlayTransition;

@interface SBLockScreenAnimatedPluginTransition : SBLockScreenPluginTransition {

	SBLockOverlayTransition* _activeToOverlayTransition;
	SBLockOverlayTransition* _activeFromOverlayTransition;
	SBLockOverlayTransition* _activeOverlayTransition;

}

@property (nonatomic,retain) SBLockOverlayTransition * activeToOverlayTransition;                //@synthesize activeToOverlayTransition=_activeToOverlayTransition - In the implementation block
@property (nonatomic,retain) SBLockOverlayTransition * activeFromOverlayTransition;              //@synthesize activeFromOverlayTransition=_activeFromOverlayTransition - In the implementation block
@property (nonatomic,retain) SBLockOverlayTransition * activeOverlayTransition;                  //@synthesize activeOverlayTransition=_activeOverlayTransition - In the implementation block
-(void)_finalizeAndClearPluginAnimationContext;
-(void)setActiveToOverlayTransition:(SBLockOverlayTransition *)arg1 ;
-(void)setActiveFromOverlayTransition:(SBLockOverlayTransition *)arg1 ;
-(void)setActiveOverlayTransition:(SBLockOverlayTransition *)arg1 ;
-(SBLockOverlayTransition *)activeToOverlayTransition;
-(SBLockOverlayTransition *)activeFromOverlayTransition;
-(SBLockOverlayTransition *)activeOverlayTransition;
-(void)beginTransition;
@end

