/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:33 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SBLockScreenNotificationListDelegate <NSObject>
@required
-(void)authenticateForNotificationActionWithCompletion:(/*^block*/id)arg1;
-(void)removeCoordinatedPresentingController:(id)arg1;
-(void)addCoordinatedPresentingController:(id)arg1;
-(void)attemptToUnlockUIFromNotification;
-(void)presentFullscreenBulletinAlertWithItem:(id)arg1;
-(void)notificationListBecomingVisible:(BOOL)arg1;
-(void)modifyFullscreenBulletinAlertWithItem:(id)arg1;
-(void)dismissFullscreenBulletinAlertWithItem:(id)arg1;
-(id)lockScreenScrollView;
-(void)bannerEnablementChanged;

@end

