/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:32 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBLockOverlayViewController.h>

@class UMUser, SBLockScreenUserPictureView;

@interface SBLockScreenUserPictureViewController : SBLockOverlayViewController {

	UMUser* _user;
	SBLockScreenUserPictureView* _userPictureView;
	BOOL _notificationListVisible;

}
-(BOOL)shouldBeHidden;
-(void)_notificationListDidAppear:(id)arg1 ;
-(void)_notificationListDidDisappear:(id)arg1 ;
-(void)loadView;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
@end

