/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:30 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoardUI/SBUIBannerItem.h>
#import <SpringBoard/SBDefaultBannerViewSource.h>
#import <libobjc.A.dylib/SBUIQuietModePlayability.h>

@protocol SBLockScreenActionHandler, SBLockScreenNotificationBannerItemDelegate;
@class SBAwayListItem, NSString;

@interface SBLockScreenNotificationBannerItem : SBUIBannerItem <SBDefaultBannerViewSource, SBUIQuietModePlayability> {

	SBAwayListItem* _listItem;
	id<SBLockScreenActionHandler> _lockedActionHandler;
	id<SBLockScreenNotificationBannerItemDelegate> _delegate;

}

@property (nonatomic,readonly) SBAwayListItem * listItem;                                                 //@synthesize listItem=_listItem - In the implementation block
@property (nonatomic,retain) id<SBLockScreenActionHandler> unlockActionHandler;                           //@synthesize lockedActionHandler=_lockedActionHandler - In the implementation block
@property (assign,nonatomic,__weak) id<SBLockScreenNotificationBannerItemDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithListItem:(id)arg1 ;
-(id)sourceDate;
-(id)attachmentImage;
-(id)lockScreenActionContext;
-(void)setUnlockActionHandler:(id<SBLockScreenActionHandler>)arg1 ;
-(id)suppressedMessage;
-(BOOL)showMessagePreview;
-(id<SBLockScreenActionHandler>)unlockActionHandler;
-(void)setDelegate:(id<SBLockScreenNotificationBannerItemDelegate>)arg1 ;
-(id<SBLockScreenNotificationBannerItemDelegate>)delegate;
-(/*^block*/id)action;
-(id)title;
-(id)subtitle;
-(id)sortDate;
-(id)message;
-(id)iconImage;
-(SBAwayListItem *)listItem;
-(id)accessoryIconMask;
-(BOOL)shouldPlayLightsAndSirens;
-(BOOL)inertWhenLocked;
-(BOOL)overridesQuietMode;
-(BOOL)overridesPocketMode;
-(BOOL)canShowWhileLocked;
-(id)attachmentText;
-(BOOL)isCritical;
@end

