/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:31 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBLockScreenNotificationCell.h>

@interface SBLockScreenBulletinCell : SBLockScreenNotificationCell
+(double)paddingBetweenTitleAndRelevanceDate;
+(double)rowHeightForTitle:(id)arg1 subtitle:(id)arg2 body:(id)arg3 maxLines:(unsigned long long)arg4 attachmentSize:(CGSize)arg5 secondaryContentSize:(CGSize)arg6 datesVisible:(BOOL)arg7 rowWidth:(double)arg8 includeUnlockActionText:(BOOL)arg9 ;
@end

