/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:30 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBLockOverlayViewController.h>

@class SBFDeviceBlockTimer, NSString;

@interface SBLockScreenDeviceBlockViewController : SBLockOverlayViewController {

	SBFDeviceBlockTimer* _blockTimer;

}

@property (nonatomic,__weak,readonly) NSString * slideToUnlockText; 
@property (nonatomic,retain) SBFDeviceBlockTimer * blockTimer;                   //@synthesize blockTimer=_blockTimer - In the implementation block
-(SBFDeviceBlockTimer *)blockTimer;
-(void)setBlockTimer:(SBFDeviceBlockTimer *)arg1 ;
-(void)dealloc;
-(void)loadView;
-(void)start;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(NSString *)slideToUnlockText;
@end

