/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:34 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBAppSwitcherPageView.h>

@interface SBMainAppSwitcherPageView : SBAppSwitcherPageView {

	long long _orientation;

}

@property (assign,nonatomic) long long orientation;                                       //@synthesize orientation=_orientation - In the implementation block
@property (nonatomic,retain) UIView*<SBMainAppSwitcherPageContentView> view; 
+(CGSize)sizeForOrientation:(long long)arg1 ;
+(double)_horizontalEdgeBorderForOrientation:(long long)arg1 ;
-(CGPoint)_centerForSubviewLayout;
-(CGAffineTransform)_scaleTransform;
-(void)setView:(id)arg1 animated:(BOOL)arg2 ;
-(CGAffineTransform)_overlayRotationTransform;
-(id)description;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)setOrientation:(long long)arg1 ;
-(long long)orientation;
-(CGRect)_viewFrame;
@end

