/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:33 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBAlertWindowViewController.h>

@interface SBMainScreenAlertWindowViewController : SBAlertWindowViewController
-(BOOL)alertWindow:(id)arg1 canAnimateInAlert:(id)arg2 ;
-(void)noteAlertWindow:(id)arg1 didDisplayAlert:(id)arg2 ;
-(void)performEndAppearanceToController:(id)arg1 withTransitionBlock:(/*^block*/id)arg2 ;
-(unsigned long long)supportedInterfaceOrientations;
-(BOOL)shouldAutorotate;
-(void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2 ;
-(void)didRotateFromInterfaceOrientation:(long long)arg1 ;
-(void)_getRotationContentSettings:(SCD_Struct_SB6*)arg1 ;
@end

