/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:32 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIControl.h>

@class NSString, UIImageView, UIView, NSMutableArray;

@interface SBNotificationsClearButton : UIControl {

	NSString* _title;
	UIImageView* _circleImageView;
	UIImageView* _xImageView;
	UIImageView* _compositeCircleXImageView;
	UIView* _highlightView;
	NSMutableArray* _glyphImageViews;
	unsigned long long _animatingTransitionCount;
	long long _graphicsQuality;
	long long _clearButtonState;

}

@property (nonatomic,readonly) long long graphicsQuality;               //@synthesize graphicsQuality=_graphicsQuality - In the implementation block
@property (nonatomic,readonly) long long clearButtonState;              //@synthesize clearButtonState=_clearButtonState - In the implementation block
+(id)_circleImageWithGraphicsQuality:(long long)arg1 ;
+(id)_xImageWithGraphicsQuality:(long long)arg1 ;
+(id)compositeCircleXImageWithGraphicsQuality:(long long)arg1 ;
-(id)initWithTitle:(id)arg1 graphicsQuality:(long long)arg2 ;
-(long long)clearButtonState;
-(id)_circleImage;
-(id)compositeCircleXImage;
-(id)_glyphImagesFromAttributedString:(id)arg1 ;
-(CGRect)_circleFrameForState:(long long)arg1 ;
-(CGRect)_xFrameWithCircleFrame:(CGRect)arg1 forState:(long long)arg2 ;
-(CGRect)_unrolledCircleBounds;
-(CGRect)_circleBoundsForState:(long long)arg1 ;
-(id)_glyphFramesWithCircleFrame:(CGRect)arg1 forState:(long long)arg2 ;
-(void)_layoutSubviewsForState:(long long)arg1 ;
-(id)_lazyHighlightView;
-(void)dealloc;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(BOOL)gestureRecognizerShouldBegin:(id)arg1 ;
-(long long)graphicsQuality;
-(void)setHighlighted:(BOOL)arg1 ;
-(id)_xImage;
-(void)setState:(long long)arg1 animated:(BOOL)arg2 ;
@end

