/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:33 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/PGPictureInPictureControllerDelegate.h>
#import <SpringBoard/SBUIActiveOrientationObserver.h>
#import <SpringBoard/SBControlCenterObserver.h>
#import <SpringBoard/SBAlertManagerObserver.h>
#import <SpringBoard/SBAlertItemsControllerObserver.h>
#import <SpringBoard/SBAssistantObserver.h>

@class PGPictureInPictureController, SBWindow, NSMutableSet, NSString;

@interface SBPIPController : NSObject <PGPictureInPictureControllerDelegate, SBUIActiveOrientationObserver, SBControlCenterObserver, SBAlertManagerObserver, SBAlertItemsControllerObserver, SBAssistantObserver> {

	PGPictureInPictureController* _pictureInPictureController;
	SBWindow* _pictureInPictureWindow;
	UIEdgeInsets _pictureInPictureWindowMargin;
	NSMutableSet* _pictureInPictureWindowHiddenReasons;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)isAutoPictureInPictureSupported;
+(id)sharedInstance;
+(BOOL)isPictureInPictureSupported;
-(void)alertManager:(id)arg1 didCreateAlertWindow:(id)arg2 ;
-(void)alertManager:(id)arg1 didTearDownAlertWindow:(id)arg2 ;
-(void)controlCenterWillPresent;
-(void)controlCenterDidDismiss;
-(void)alertItemsController:(id)arg1 willActivateAlertItem:(id)arg2 ;
-(void)alertItemsController:(id)arg1 didActivateAlertItem:(id)arg2 ;
-(void)alertItemsController:(id)arg1 didDeactivateAlertItem:(id)arg2 forReason:(int)arg3 ;
-(void)controlCenterWillBeginTransition;
-(void)controlCenterDidFinishTransition;
-(id)_pipWindow;
-(void)setPictureInPictureWindowHidden:(BOOL)arg1 withReason:(id)arg2 ;
-(BOOL)isPictureInPictureWindowVisible;
-(void)assistant:(id)arg1 viewWillAppear:(long long)arg2 ;
-(void)assistant:(id)arg1 viewDidDisappear:(long long)arg2 ;
-(BOOL)shouldStartPictureInPictureForApplicationWithProcessIdentifierEnteringBackground:(int)arg1 ;
-(void)startPictureInPictureForApplicationWithProcessIdentifierEnteringBackground:(int)arg1 animated:(BOOL)arg2 completionHandler:(/*^block*/id)arg3 ;
-(BOOL)_pointInside:(CGPoint)arg1 ;
-(void)setPictureInPictureWindowMargin:(UIEdgeInsets)arg1 animationDuration:(double)arg2 animationOptions:(unsigned long long)arg3 ;
-(void)_appSwitcherWillQuitApp:(id)arg1 ;
-(void)_nowPlayingStateChangedForPartialMedusaDevice;
-(void)_managePictureInPictureWindowVisibilityAnimated:(BOOL)arg1 ;
-(id)_pictureInPictureApplicationForProcessIdentifier:(int)arg1 ;
-(void)_managePictureInPictureWindowLevel;
-(void)_createWindowAndRootViewControllerIfNeeded;
-(void)_destroyWindowAndRootViewControllerIfPossible;
-(void)dealloc;
-(id)init;
-(void)pictureInPictureController:(id)arg1 didCreatePictureInPictureViewController:(id)arg2 ;
-(void)pictureInPictureController:(id)arg1 willDestroyPictureInPictureViewController:(id)arg2 ;
-(void)pictureInPictureInterruptionBegan;
-(void)pictureInPictureInterruptionEnded;
-(void)activeInterfaceOrientationWillChangeToOrientation:(long long)arg1 ;
-(void)activeInterfaceOrientationDidChangeToOrientation:(long long)arg1 willAnimateWithDuration:(double)arg2 fromOrientation:(long long)arg3 ;
-(void)_lockStateDidChange:(id)arg1 ;
@end

