/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:32 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <SpringBoard/SpringBoard-Structs.h>
@class FBSDisplay, SBUserSessionController, MCProfileConnection;

@interface SBPolicyAggregator : NSObject {

	FBSDisplay* _display;
	SBUserSessionController* _lazy_userSessionController;
	MCProfileConnection* _lazy_profileConnection;
	CFBooleanRef _hasCameraCapability;

}

@property (setter=_setUserSessionController:,getter=_userSessionController,nonatomic,retain) SBUserSessionController * userSessionController;              //@synthesize lazy_userSessionController=_lazy_userSessionController - In the implementation block
@property (setter=_setProfileConnection:,getter=_profileConnection,nonatomic,retain) MCProfileConnection * profileConnection;                              //@synthesize lazy_profileConnection=_lazy_profileConnection - In the implementation block
-(BOOL)allowsCapability:(long long)arg1 ;
-(BOOL)allowsCapability:(long long)arg1 explanation:(id*)arg2 ;
-(id)_userSessionController;
-(BOOL)allowsTransitionRequest:(id)arg1 ;
-(BOOL)_allowsCapabilitySuggestedApplicationWithExplanation:(id*)arg1 ;
-(BOOL)_allowsCapabilityLockScreenBulletinWithExplanation:(id*)arg1 ;
-(BOOL)_allowsCapabilityUnlockToPluginSpecifiedApplicationWithExplanation:(id*)arg1 ;
-(BOOL)_allowsCapabilityAssistantEnabledWithExplanation:(id*)arg1 ;
-(BOOL)_allowsCapabilityAssistantWithExplanation:(id*)arg1 ;
-(BOOL)_allowsCapabilitySendMediaCommandWithExplanation:(id*)arg1 ;
-(BOOL)_allowsCapabilitySystemGestureWithExplanation:(id*)arg1 ;
-(BOOL)_allowsCapabilityVoiceControlWithExplanation:(id*)arg1 ;
-(BOOL)_allowsCapabilitySpotlightWithExplanation:(id*)arg1 ;
-(BOOL)_allowsCapabilityLockScreenCameraSupportedWithExplanation:(id*)arg1 ;
-(BOOL)_allowsCapabilityLockScreenCameraWithExplanation:(id*)arg1 ;
-(BOOL)_allowsCapabilityNotificationCenterWithExplanation:(id*)arg1 ;
-(BOOL)_allowsCapabilityControlCenterWithExplanation:(id*)arg1 ;
-(BOOL)_allowsCapabilityLogoutWithExplanation:(id*)arg1 ;
-(BOOL)_allowsCapabilityLoginWindowWithExplanation:(id*)arg1 ;
-(BOOL)_allowsCapabilityHomeScreenEditingWithExplanation:(id*)arg1 ;
-(BOOL)_allowsCapabilityScreenshotWithExplanation:(id*)arg1 ;
-(BOOL)_allowsCapabilityCommandTabWithExplanation:(id*)arg1 ;
-(BOOL)_isWhitelistedApplicationAllowedToLaunchInLoginWindow:(id)arg1 ;
-(BOOL)_hasFullySetUpUserWithExplanation:(id*)arg1 ;
-(BOOL)_allowsNotificationOrControlCenterWithExplanation:(id*)arg1 ;
-(id)_profileConnection;
-(void)_setUserSessionController:(id)arg1 ;
-(void)_setProfileConnection:(id)arg1 ;
-(id)initWithDisplay:(id)arg1 ;
@end

