/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:29 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SBPowerDownViewDelegate
@required
-(void)powerDownViewRequestCancel:(id)arg1;
-(void)powerDownViewRequestPowerDown:(id)arg1;
-(void)powerDownViewAnimateOutCompleted:(id)arg1;

@end

