/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:29 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@interface SBRootFolderDockAnimationViewController : UIViewController {

	long long _forcedInterfaceOrientation;

}

@property (assign,nonatomic) long long forcedInterfaceOrientation;              //@synthesize forcedInterfaceOrientation=_forcedInterfaceOrientation - In the implementation block
-(void)setForcedInterfaceOrientation:(long long)arg1 ;
-(long long)forcedInterfaceOrientation;
-(unsigned long long)supportedInterfaceOrientations;
-(BOOL)shouldAutorotate;
@end

