/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:33 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SBSoftwareUpdateInstallOptions : NSObject {

	BOOL _automaticInstallAttempt;
	BOOL _installDark;

}

@property (assign,nonatomic) BOOL automaticInstallAttempt;              //@synthesize automaticInstallAttempt=_automaticInstallAttempt - In the implementation block
@property (assign,nonatomic) BOOL installDark;                          //@synthesize installDark=_installDark - In the implementation block
-(BOOL)automaticInstallAttempt;
-(BOOL)installDark;
-(void)setAutomaticInstallAttempt:(BOOL)arg1 ;
-(void)setInstallDark:(BOOL)arg1 ;
-(id)description;
@end

