/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:33 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface SBSpuriousScreenUndimmingAssertion : NSObject {

	NSString* _identifier;

}
+(void)_accessListWithBlock:(/*^block*/id)arg1 ;
+(BOOL)isAnyActive;
+(id)debugDescription;
-(void)dealloc;
-(id)description;
-(void)invalidate;
-(id)initWithIdentifier:(id)arg1 ;
@end

