/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:31 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBDosidoAnimator.h>

@class CAMutableMeshTransform, UIView, SBStretchTransformerView, NSString;

@interface SBStretchTransformer : NSObject <SBDosidoAnimator> {

	double _percentage;
	CAMutableMeshTransform* _mesh;
	/*^block*/id _completionBlock;
	double _stretchFactor;
	UIView* _parentView;
	SBStretchTransformerView* _transformView;
	UIView* _view;
	unsigned long long _anchorEdge;
	long long _orientation;

}

@property (nonatomic,retain) UIView * view;                                //@synthesize view=_view - In the implementation block
@property (assign,nonatomic) unsigned long long anchorEdge;                //@synthesize anchorEdge=_anchorEdge - In the implementation block
@property (assign,nonatomic) long long orientation;                        //@synthesize orientation=_orientation - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (getter=isStepped,nonatomic,readonly) BOOL stepped; 
@property (assign,nonatomic) double stepPercentage; 
-(double)stepPercentage;
-(void)setStepPercentage:(double)arg1 ;
-(void)animateDosidoWithFactory:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)cancelDosido;
-(void)finishSteppingForwardToEnd;
-(void)finishSteppingBackwardToStart;
-(BOOL)isStepped;
-(id)initWithParentView:(id)arg1 anchorEdge:(unsigned long long)arg2 orientation:(long long)arg3 ;
-(void)_setAnchorEdge:(unsigned long long)arg1 ;
-(void)_setOrientation:(long long)arg1 ;
-(void)_setStretchFactor:(double)arg1 ;
-(void)_animateToZeroStretchFactor;
-(void)updateMeshTransform:(id)arg1 stretchFactor:(double)arg2 ;
-(unsigned long long)anchorEdge;
-(void)dealloc;
-(UIView *)view;
-(long long)orientation;
-(void)setView:(UIView *)arg1 ;
-(void)animationDidStop:(id)arg1 finished:(BOOL)arg2 ;
@end

