/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:29 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBFolderView.h>

@class UIButton, SBStarkIconLayoutOverrideStrategy;

@interface SBStarkFolderView : SBFolderView {

	BOOL _buttonUXEnabled;
	UIButton* _scrollLeftButton;
	UIButton* _scrollRightButton;
	CGSize _scrollButtonSize;
	SBStarkIconLayoutOverrideStrategy* _iconLayoutOverrideStrategy;
	UIEdgeInsets _listViewInsets;

}

@property (nonatomic,retain) SBStarkIconLayoutOverrideStrategy * iconLayoutOverrideStrategy; 
-(id)initWithFolder:(id)arg1 orientation:(long long)arg2 viewMap:(id)arg3 context:(id)arg4 ;
-(void)_scrollButtonPressed:(id)arg1 ;
-(void)_updateScrollButtonStatesForIndex:(long long)arg1 ;
-(void)resetIconListViews;
-(void)_evaluateScrollingForListViewsIfNecessary;
-(void)updateIconListViews;
-(void)_updateIconListFrames;
-(void)_updatePageControlToIndex:(long long)arg1 ;
-(id)initWithFolder:(id)arg1 orientation:(long long)arg2 viewMap:(id)arg3 ;
-(void)setInteractionAffordances:(unsigned long long)arg1 ;
-(SBStarkIconLayoutOverrideStrategy *)iconLayoutOverrideStrategy;
-(void)setIconLayoutOverrideStrategy:(SBStarkIconLayoutOverrideStrategy *)arg1 ;
-(id)_newPageControl;
-(double)_offsetToCenterPageControlInSpaceForPageControl;
-(BOOL)shouldInstallFocusGuides;
-(void)_layoutSubviews;
@end

