/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:32 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBStarkAlertToAppWorkspaceTransaction.h>

@class SBAlert, SBWorkspaceAlert;

@interface SBStarkAlertToImpersonatedAppWorkspaceTransaction : SBStarkAlertToAppWorkspaceTransaction {

	SBAlert* _fromAlert;
	SBWorkspaceAlert* _toAlert;

}
-(id)initWithTransitionRequest:(id)arg1 ;
-(id)_effectiveTopEntity;
-(void)_beginAnimation;
-(void)_activateAlert;
-(void)_alertDidDeactivate;
-(void)dealloc;
-(id)debugDescription;
@end

