/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:32 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBScreenConnectionHandler.h>
#import <SpringBoard/SBStarkScreenControllerDelegate.h>

@class NSMutableDictionary, SBStarkScreenController, NSHashTable, SBSpuriousScreenUndimmingAssertion, SBPasscodeLockDisableAssertion, SBLockScreenDisableAssertion, SBSStatusBarStyleOverridesAssertion, NSString;

@interface SBStarkScreenManager : NSObject <SBScreenConnectionHandler, SBStarkScreenControllerDelegate> {

	NSMutableDictionary* _displayToControllerMap;
	SBStarkScreenController* _currentScreenController;
	NSHashTable* _observers;
	SBSpuriousScreenUndimmingAssertion* _spuriousScreenUndimmingAssertion;
	SBPasscodeLockDisableAssertion* _deviceLockDisableAssertion;
	SBLockScreenDisableAssertion* _lockScreenDisableAssertion;
	SBPasscodeLockDisableAssertion* _earlyConnectDeviceLockDisableAssertion;
	SBSStatusBarStyleOverridesAssertion* _carPlayStatusBarStyleOverrideAssertion;
	SBSStatusBarStyleOverridesAssertion* _earlyCarPlayStatusBarStyleOverrideAssertion;
	BOOL _hasShownConnectedAlert;
	BOOL _delayShowingConnectedAlert;
	BOOL _geoSupported;
	BOOL _earlyStarkConnection;
	BOOL _delayUpdatingLockOutMode;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)starkScreenIsAttached;
+(id)sharedInstance;
-(BOOL)isStarkActive;
-(id)currentScreenController;
-(BOOL)starkScreenIsAttached;
-(id)activeScreenController;
-(BOOL)isGeoSupported;
-(BOOL)screenManager:(id)arg1 shouldBindConnectionHandlerToScreen:(id)arg2 ;
-(void)screenManager:(id)arg1 didTriggerConnectionHandlerEvent:(long long)arg2 forScreen:(id)arg3 ;
-(id)screenControllerForDisplay:(id)arg1 ;
-(BOOL)starkScreenControllerShouldDelayUpdateLockoutMode:(id)arg1 ;
-(void)starkScreenControllerWantsRelockUI:(id)arg1 ;
-(void)_usbStarkConnected;
-(void)_pairedVehiclesChanged:(id)arg1 ;
-(void)_updateGeoSupport;
-(BOOL)promptRelockUIIfAppropriate;
-(void)_earlyStarkConnection;
-(void)_clearEarlyConnectState;
-(void)_promptConnectionSteps;
-(void)_scheduleClearEarlyConnectStateExpirationTimer;
-(void)_unscheduleClearEarlyConnectStateExpirationTimer;
-(void)_clearEarlyConnectStateTimerExpired;
-(void)_clearPromptState;
-(void)_setCurrentController:(id)arg1 ;
-(void)prepareToHandleUnlockAttempt;
-(BOOL)handleUnlockAttempt;
-(BOOL)shouldShowCarPlayStatusBarItem;
-(void)dealloc;
-(id)init;
-(NSString *)description;
-(void)addObserver:(id)arg1 ;
-(void)removeObserver:(id)arg1 ;
@end

