/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:32 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <SpringBoard/SpringBoard-Structs.h>
@interface SBStarkIconLayoutOverrideStrategy : NSObject {

	UIEdgeInsets _layoutInsets;
	BOOL _preservesCurrentListOrigin;

}

@property (nonatomic,readonly) UIEdgeInsets layoutInsets;                    //@synthesize layoutInsets=_layoutInsets - In the implementation block
@property (nonatomic,readonly) BOOL preservesCurrentListOrigin;              //@synthesize preservesCurrentListOrigin=_preservesCurrentListOrigin - In the implementation block
-(BOOL)preservesCurrentListOrigin;
-(UIEdgeInsets)layoutInsets;
-(id)initWithFullscreenOverrideStrategyForConfiguration:(id)arg1 ;
@end

