/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:33 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBSwitcherWallpaperPageContentView.h>

@class SBOrientationTransformWrapperView, UIView, SBWindowSelfHostWrapper, SBAppSwitcherSettings;

@interface SBSwitcherMetahostingHomePageContentView : SBSwitcherWallpaperPageContentView {

	SBOrientationTransformWrapperView* _portraitContentWrapper;
	SBOrientationTransformWrapperView* _rotatingContentWrapper;
	UIView* _darkeningView;
	SBWindowSelfHostWrapper* _iconsWindowHostWrapper;
	UIView* _snapshotView;
	SBWindowSelfHostWrapper* _statusBarWindowHostWrapper;
	UIView* _fakeStatusBar;
	SBAppSwitcherSettings* _settings;
	BOOL _presenting;
	BOOL _interactive;

}
+(BOOL)_usesSnapshots;
-(void)viewPresenting:(id)arg1 withInteraction:(BOOL)arg2 andInitialProgress:(double)arg3 forTransitionRequest:(id)arg4 ;
-(void)viewDismissing:(id)arg1 withInteraction:(BOOL)arg2 andInitialProgress:(double)arg3 forTransitionRequest:(id)arg4 ;
-(void)updateTransitionProgress:(double)arg1 ;
-(void)interactionDidEnd:(BOOL)arg1 ;
-(void)transitionDidEnd:(BOOL)arg1 forPresentation:(BOOL)arg2 ;
-(void)_createFakeStatusBar;
-(long long)_targetWallpaperStyle;
-(double)_darkeningFactor;
-(void)_transitionWallpaperWithProgress:(double)arg1 presenting:(BOOL)arg2 ;
-(void)_removeSnapshotIfNecessary;
-(void)_substituteSnapshotIfNecessary;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(void)setOrientation:(long long)arg1 ;
-(void)setCornerRadius:(double)arg1 ;
-(BOOL)_shouldAnimatePropertyWithKey:(id)arg1 ;
-(double)cornerRadius;
-(void)willMoveToWindow:(id)arg1 ;
@end

