/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:29 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSTimer, SBPasscodeLockDisableAssertion, SBAppStatusBarSettingsAssertion;

@interface SBSyncController : NSObject {

	int _restoreState;
	int _resetState;
	int _restoreTimerState;
	NSTimer* _restoreTimer;
	NSTimer* _progressTimer;
	BOOL _showingResetUI;
	BOOL _appsChangedDuringSync;
	int _restoreStartedNotifyToken;
	int _restoreEndedNotifyToken;
	SBPasscodeLockDisableAssertion* _disableDeviceLockAssertion;
	SBAppStatusBarSettingsAssertion* _hideStatusBarAssertion;
	BOOL _isAppSyncing;
	BOOL _inExtendedAppSyncCoalescePeriod;

}
+(id)sharedInstance;
-(BOOL)isResetting;
-(void)finishedTerminatingApplications;
-(void)beginRestoring;
-(void)_didEndRestoring:(int)arg1 ;
-(void)_resetStarted:(id)arg1 ;
-(void)_resetEnded:(id)arg1 ;
-(void)_wirelessSyncEnded:(id)arg1 ;
-(void)_wirelessSyncBegan:(id)arg1 ;
-(void)_appInstallationNotification;
-(void)_notifyRestoreCanProceed;
-(void)_setupRestoreTimer;
-(void)_killApplications;
-(void)_delayedBeginReset;
-(void)_syncSessionDidBegin;
-(void)_syncSessionDidEnd;
-(void)_didEndResetting;
-(void)_rebootNow;
-(void)_invalidateRestoreTimer;
-(void)_finishEndRestoring;
-(void)_delayedQuitApplications;
-(BOOL)_isBackupAgentRunning;
-(void)_restoreTimerFired:(id)arg1 ;
-(void)cancelRestoring;
-(void)beginResetting:(BOOL)arg1 ;
-(void)dealloc;
-(void)_updateProgress;
-(void)startObserving;
-(BOOL)isRestoring;
-(int)resetState;
-(int)restoreState;
-(void)_setRestoreState:(int)arg1 ;
-(void)stopObserving;
-(BOOL)isInUse;
@end

