/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:33 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoardFoundation/_SBFVibrantTableViewCell.h>
#import <SpringBoard/SBModalLayoutCaching.h>

@class UILabel, UIImageView, NSString;

@interface SBTodayTableViewCell : _SBFVibrantTableViewCell <SBModalLayoutCaching> {

	UILabel* _label;
	UIImageView* _iconImageView;
	long long _layoutMode;

}

@property (assign,nonatomic) CGRect textRect; 
@property (nonatomic,copy) NSString * labelText; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) long long layoutMode;                  //@synthesize layoutMode=_layoutMode - In the implementation block
+(double)interCellSpacingInLayoutMode:(long long)arg1 ;
+(double)snippetLineHeight;
+(id)defaultFontColor;
+(id)defaultFont;
+(id)defaultTextAttributes;
-(void)setLayoutMode:(long long)arg1 ;
-(void)setTextRect:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 ;
-(void)setIcon:(id)arg1 ;
-(CGRect)textRect;
-(NSString *)labelText;
-(void)setLabelText:(NSString *)arg1 ;
-(long long)layoutMode;
@end

