/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:29 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBUIMainScreenAnimationController.h>

@class SBSceneLayoutAnimationWrapperView, UIView;

@interface SBUIBootToUserSetupAppZoomInAnimationController : SBUIMainScreenAnimationController {

	SBSceneLayoutAnimationWrapperView* _layoutAnimationWrapperView;
	UIView* _snapshotView;

}
-(id)initWithTransitionContextProvider:(id)arg1 ;
-(id)_getTransitionWindow;
-(void)_finishedZooming;
-(void)_cleanupAnimation;
-(BOOL)_waitsForApplicationActivationIfNecessary;
-(id)_animationProgressDependencies;
-(void)_prepareAnimation;
-(void)_setHidden:(BOOL)arg1 ;
-(void)_startAnimation;
@end

