/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:29 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBUIAnimationController.h>

@class SBWorkspaceTransitionRequest;

@interface SBUIWorkspaceAnimationController : SBUIAnimationController {

	/*^block*/id _transitionAnimation;

}

@property (nonatomic,readonly) SBWorkspaceTransitionRequest * workspaceTransitionRequest; 
@property (nonatomic,copy) id transitionAnimation;                                                     //@synthesize transitionAnimation=_transitionAnimation - In the implementation block
-(id)initWithTransitionContextProvider:(id)arg1 ;
-(void)_noteAnimationDidCommit:(BOOL)arg1 withSettings:(id)arg2 ;
-(void)_setInteractiveApplicationTransitionAnimationPercentage:(double)arg1 ;
-(void)_animateInteractiveApplicationTransitionFromPercentage:(double)arg1 toPercentage:(double)arg2 withSettings:(id)arg3 ;
-(id)initWithWorkspaceTransitionRequest:(id)arg1 ;
-(id)transitionAnimation;
-(SBWorkspaceTransitionRequest *)workspaceTransitionRequest;
-(void)setTransitionAnimation:(id)arg1 ;
@end

