/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:30 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBUIStarkStartupAnimation.h>

@class NSMutableArray, SBStarkLockOutView;

@interface SBUIStarkStartupToLockoutAnimation : SBUIStarkStartupAnimation {

	NSMutableArray* _viewsToSlideUp;
	SBStarkLockOutView* _toLockoutView;
	unsigned long long _significantAnimationsRemaining;

}
-(void)_cleanupAnimation;
-(void)_prepareAnimation;
-(void)_slideUpViewsWithSlideFactory:(id)arg1 fadeFactory:(id)arg2 delayIncrement:(double)arg3 ;
-(void)_noteSignificantAnimationFinished;
-(void)_finishViewForSlideUp:(id)arg1 ;
-(id)initFromLockoutView:(id)arg1 toLockoutView:(id)arg2 starkScreenController:(id)arg3 ;
-(void)_startAnimation;
@end

