/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:33 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBUIWorkspaceAnimationController.h>

@class SBWorkspaceTransitionRequest;

@interface SBUIMainScreenAnimationController : SBUIWorkspaceAnimationController

@property (nonatomic,readonly) SBWorkspaceTransitionRequest * transitionRequest; 
-(SBWorkspaceTransitionRequest *)transitionRequest;
-(id)initWithTransitionContextProvider:(id)arg1 ;
-(id)_getTransitionWindow;
-(void)_cleanupAnimation;
-(id)initWithWorkspaceTransitionRequest:(id)arg1 ;
-(id)activatingApp;
-(id)deactivatingApp;
-(void)_dismissBannerAnimated:(BOOL)arg1 ;
-(void)_removeWallpaperAnimationPriorityWithFactory:(id)arg1 ;
-(BOOL)_shouldDismissBanner;
-(void)__startAnimation;
-(id)_primaryAppOrAnyAppFromSet:(id)arg1 ;
-(void)_begin;
@end

