/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:33 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBUIAnimationController.h>
#import <SpringBoard/SBUIAnimationControllerObserver.h>

@class NSMutableArray, NSArray, NSString;

@interface SBUIAnimationControllerGroup : SBUIAnimationController <SBUIAnimationControllerObserver> {

	BOOL _finished;
	NSMutableArray* _animations;

}

@property (nonatomic,readonly) NSArray * animations;                //@synthesize animations=_animations - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)animationController:(id)arg1 willBeginAnimation:(BOOL)arg2 ;
-(void)animationControllerDidFinishAnimation:(id)arg1 ;
-(BOOL)_willAnimate;
-(BOOL)waitingToStart;
-(void)_forEachAnimation:(/*^block*/id)arg1 ;
-(id)init;
-(NSString *)description;
-(NSArray *)animations;
-(void)addAnimation:(id)arg1 ;
-(id)initWithAnimations:(id)arg1 ;
-(void)_startAnimation;
@end

