/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:31 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBUIStarkDosidoAnimation.h>

@class NSNumber;

@interface SBUIStarkDosidoNowPlayingAnimation : SBUIStarkDosidoAnimation {

	NSNumber* _activatedNowPlaying;
	BOOL _waitForNowPlaying;

}
-(void)_cleanupAnimation;
-(BOOL)_waitsForApplicationActivationIfNecessary;
-(id)initFromApp:(id)arg1 toNowPlayingWithStarkScreenController:(id)arg2 ;
-(id)initFromNowPlayingToAlertImpersonator:(id)arg1 starkScreenController:(id)arg2 ;
-(void)_setupStartDependencies;
-(void)_commonInitWaitForNowPlaying:(BOOL)arg1 fromView:(id)arg2 toView:(id)arg3 alert:(id)arg4 toDisplay:(id)arg5 ;
-(id)initFromNowPlayingToNowPlayingWithStarkScreenController:(id)arg1 ;
-(id)initFromNowPlayingToApp:(id)arg1 starkScreenController:(id)arg2 ;
-(id)initFromAlertImpersonator:(id)arg1 toNowPlayingWithStarkScreenController:(id)arg2 ;
-(void)_startAnimation;
@end

