/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:29 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <SpringBoard/SpringBoard-Structs.h>
@interface SBUserNotificationCenter : NSObject
+(void)startUserNotificationCenter;
+(void)_userNotificationDone:(id)arg1 ;
+(void)dispatchUserNotificationFromMachMessage:(SCD_Struct_SB18*)arg1 auditToken:(const SCD_Struct_SB19*)arg2 ;
@end

