/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:32 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class UIImageView, UIButton;

@interface SBWidgetsSettingsTableViewCell : UITableViewCell {

	UIImageView* _dotImageView;
	BOOL _widgetEnabled;
	BOOL _showsDot;
	UIButton* _insertWidgetAccessoryButton;

}

@property (assign,getter=isWidgetEnabled,nonatomic) BOOL widgetEnabled;                    //@synthesize widgetEnabled=_widgetEnabled - In the implementation block
@property (assign,nonatomic) BOOL showsDot;                                                //@synthesize showsDot=_showsDot - In the implementation block
@property (nonatomic,__weak,readonly) UIButton * insertWidgetAccessoryButton;              //@synthesize insertWidgetAccessoryButton=_insertWidgetAccessoryButton - In the implementation block
-(void)setShowsDot:(BOOL)arg1 ;
-(BOOL)showsDot;
-(UIButton *)insertWidgetAccessoryButton;
-(void)layoutSubviews;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 ;
-(void)setWidgetEnabled:(BOOL)arg1 ;
-(BOOL)isWidgetEnabled;
@end

