/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:32 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@protocol SBWidgetViewControllerDelegate;
@class NSString, BSAuditToken;

@interface SBWidgetViewController : UIViewController {

	BOOL _hasContent;
	long long _requestState;
	BOOL _implementsPerformUpdate;
	NSString* _appBundleID;
	NSString* _widgetIdentifier;
	BSAuditToken* _auditToken;
	id<SBWidgetViewControllerDelegate> _delegate;

}

@property (assign,nonatomic) long long requestState;                                          //@synthesize requestState=_requestState - In the implementation block
@property (nonatomic,copy,readonly) NSString * widgetIdentifier;                              //@synthesize widgetIdentifier=_widgetIdentifier - In the implementation block
@property (nonatomic,copy) NSString * appBundleID;                                            //@synthesize appBundleID=_appBundleID - In the implementation block
@property (nonatomic,__weak,readonly) BSAuditToken * auditToken;                              //@synthesize auditToken=_auditToken - In the implementation block
@property (assign,nonatomic,__weak) id<SBWidgetViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) BOOL hasContent;                                                 //@synthesize hasContent=_hasContent - In the implementation block
@property (getter=isInternal,nonatomic,readonly) BOOL internal; 
@property (nonatomic,readonly) BOOL implementsPerformUpdate;                                  //@synthesize implementsPerformUpdate=_implementsPerformUpdate - In the implementation block
+(id)_requestLocalViewControllerOfClass:(Class)arg1 context:(id)arg2 handler:(/*^block*/id)arg3 ;
+(id)widgetViewControllerWithIdentifier:(id)arg1 bundlePath:(id)arg2 ;
+(id)requestViewController:(id)arg1 context:(id)arg2 handler:(/*^block*/id)arg3 ;
-(void)updateContentWidth:(double)arg1 ;
-(void)invalidateCachedSnapshotWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)disconnectRemoteViewControllerWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)insertSnapshotWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)captureSnapshotWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)requestInsertionOfRemoteViewWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)performUpdateWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)connectRemoteViewControllerWithCompletionHandler:(/*^block*/id)arg1 ;
-(BOOL)implementsPerformUpdate;
-(id)initWithWidgetIdentifier:(id)arg1 bundlePath:(id)arg2 ;
-(void)beginAppearanceTransition:(BOOL)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(void)endAppearanceTransitionWithCompletion:(/*^block*/id)arg1 ;
-(void)_disconnectRemoteViewControllerImmediatelyWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)validateSnapshotViewForActiveLayoutMode;
-(void)setHasContent:(BOOL)arg1 ;
-(void)_requestLaunchOfURL:(id)arg1 ;
-(void)requestPreferredViewHeightWithHandler:(/*^block*/id)arg1 ;
-(void)setDelegate:(id<SBWidgetViewControllerDelegate>)arg1 ;
-(id<SBWidgetViewControllerDelegate>)delegate;
-(BOOL)hasContent;
-(long long)requestState;
-(void)setRequestState:(long long)arg1 ;
-(BSAuditToken *)auditToken;
-(id)_cancelTouches;
-(BOOL)isInternal;
-(void)hostWillPresent;
-(void)hostDidPresent;
-(void)hostWillDismiss;
-(void)hostDidDismiss;
-(NSString *)widgetIdentifier;
-(NSString *)appBundleID;
-(void)setAppBundleID:(NSString *)arg1 ;
@end

