/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:28 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBUIAnimationControllerTransitionContextProvider.h>
#import <SpringBoard/SBWorkspaceTransitionLayoutDelegate.h>
#import <libobjc.A.dylib/BSDescriptionProviding.h>

@class NSSet, FBSDisplay, SBWorkspace, SBAlertManager, NSUUID, NSString, SBSceneLayoutViewController, SBWorkspaceApplicationTransitionContext, SBWorkspaceAlertTransitionContext, BSAuditToken;

@interface SBWorkspaceTransitionRequest : NSObject <SBUIAnimationControllerTransitionContextProvider, SBWorkspaceTransitionLayoutDelegate, BSDescriptionProviding> {

	FBSDisplay* _display;
	SBWorkspace* _workspace;
	SBAlertManager* _alertManager;
	NSUUID* _uniqueID;
	NSString* _eventLabel;
	SBSceneLayoutViewController* _appLayoutController;
	/*^block*/id _transitionCompletion;
	BOOL _finalized;
	long long _interfaceOrientation;
	SBWorkspaceApplicationTransitionContext* _applicationContext;
	SBWorkspaceAlertTransitionContext* _alertContext;
	BSAuditToken* _auditToken;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,copy,readonly) NSSet * activatingApps; 
@property (nonatomic,copy,readonly) NSSet * deactivatingApps; 
@property (nonatomic,readonly) BOOL isMainWorkspaceTransitionRequest; 
@property (nonatomic,readonly) FBSDisplay * display;                                                    //@synthesize display=_display - In the implementation block
@property (nonatomic,retain) BSAuditToken * auditToken;                                                 //@synthesize auditToken=_auditToken - In the implementation block
@property (nonatomic,retain) SBAlertManager * alertManager;                                             //@synthesize alertManager=_alertManager - In the implementation block
@property (nonatomic,copy) NSString * eventLabel;                                                       //@synthesize eventLabel=_eventLabel - In the implementation block
@property (nonatomic,copy,readonly) NSUUID * uniqueID;                                                  //@synthesize uniqueID=_uniqueID - In the implementation block
@property (getter=isFinalized,nonatomic,readonly) BOOL finalized;                                       //@synthesize finalized=_finalized - In the implementation block
@property (nonatomic,retain) SBWorkspaceApplicationTransitionContext * applicationContext;              //@synthesize applicationContext=_applicationContext - In the implementation block
@property (nonatomic,retain) SBWorkspaceAlertTransitionContext * alertContext;                          //@synthesize alertContext=_alertContext - In the implementation block
@property (nonatomic,copy) id transitionCompletion;                                                     //@synthesize transitionCompletion=_transitionCompletion - In the implementation block
@property (nonatomic,readonly) SBWorkspace * workspace;                                                 //@synthesize workspace=_workspace - In the implementation block
-(NSSet *)activatingApps;
-(NSSet *)deactivatingApps;
-(BOOL)isMainWorkspaceTransitionRequest;
-(void)modifyApplicationContext:(/*^block*/id)arg1 ;
-(void)setEventLabel:(NSString *)arg1 ;
-(void)setTransitionCompletion:(id)arg1 ;
-(SBAlertManager *)alertManager;
-(void)modifyAlertContext:(/*^block*/id)arg1 ;
-(void)setEventLabelWithFormat:(id)arg1 ;
-(SBWorkspaceAlertTransitionContext *)alertContext;
-(void)declineWithReason:(id)arg1 ;
-(NSString *)eventLabel;
-(void)setAlertManager:(SBAlertManager *)arg1 ;
-(id)initWithWorkspace:(id)arg1 display:(id)arg2 ;
-(void)setAlertContext:(SBWorkspaceAlertTransitionContext *)arg1 ;
-(void)_sendResult:(BOOL)arg1 ;
-(id)layoutStateForTransitionContext:(id)arg1 ;
-(id)originalLayoutStateForTransitionContext:(id)arg1 ;
-(CGRect)transitionContext:(id)arg1 referenceFrameForEntity:(id)arg2 ;
-(BOOL)isFinalized;
-(id)transitionCompletion;
-(id)init;
-(NSString *)description;
-(FBSDisplay *)display;
-(BSAuditToken *)auditToken;
-(void)setAuditToken:(BSAuditToken *)arg1 ;
-(SBWorkspaceApplicationTransitionContext *)applicationContext;
-(void)setApplicationContext:(SBWorkspaceApplicationTransitionContext *)arg1 ;
-(id)descriptionWithMultilinePrefix:(id)arg1 ;
-(id)succinctDescription;
-(id)succinctDescriptionBuilder;
-(id)descriptionBuilderWithMultilinePrefix:(id)arg1 ;
-(SBWorkspace *)workspace;
-(NSUUID *)uniqueID;
-(void)finalize;
@end

