/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:34 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct CGSize {
	double width;
	double height;
} CGSize;

typedef struct CGPoint {
	double x;
	double y;
} CGPoint;

typedef struct CGRect {
	CGPoint origin;
	CGSize size;
} CGRect;

typedef struct __IOHIDEvent* IOHIDEventRef;

typedef struct __CFBoolean* CFBooleanRef;

typedef struct __GSEvent* GSEventRef;

typedef struct {
	BOOL field1;
	BOOL field2;
	BOOL field3;
	BOOL field4;
	BOOL field5;
	double field6;
	int field7;
} SCD_Struct_SB6;

typedef struct _NSZone* NSZoneRef;

typedef struct UIEdgeInsets {
	double top;
	double left;
	double bottom;
	double right;
} UIEdgeInsets;

typedef struct opaque_pthread_mutex_t {
	long long __sig;
	char __opaque[56];
} opaque_pthread_mutex_t;

typedef struct __CTServerConnection* CTServerConnectionRef;

typedef struct __CFString* CFStringRef;

typedef struct __SCDynamicStore* SCDynamicStoreRef;

typedef struct tcp_connection_fallback_watch_s* tcp_connection_fallback_watch_sRef;

typedef struct {
	int field1;
	int field2;
} SCD_Struct_SB14;

typedef struct CGColor* CGColorRef;

typedef struct {
	unsigned field1;
	unsigned field2;
	unsigned field3;
	unsigned field4;
	unsigned field5;
	int field6;
} SCD_Struct_SB16;

typedef struct {
	unsigned field1;
} SCD_Struct_SB17;

typedef struct {
	SCD_Struct_SB16 field1;
	SCD_Struct_SB17 field2;
} SCD_Struct_SB18;

typedef struct {
	unsigned field1[8];
} SCD_Struct_SB19;

typedef struct {
	long long startStyle;
	long long endStyle;
	double transitionFraction;
} SCD_Struct_SB20;

typedef struct __CFDictionary* CFDictionaryRef;

typedef struct __CFRunLoop* CFRunLoopRef;

typedef struct __WiFiManagerClient* WiFiManagerClientRef;

typedef struct __WiFiDeviceClient* WiFiDeviceClientRef;

typedef struct __WiFiNetwork* WiFiNetworkRef;

typedef struct SBIconCoordinate {
	long long row;
	long long col;
} SBIconCoordinate;

typedef struct NSRange {
	unsigned long long location;
	unsigned long long length;
} NSRange;

typedef struct {
	float field1;
	__CFArray field2;
	float field3;
} SCD_Struct_SB28;

typedef struct {
	unsigned long long field1;
	unsigned long long field2;
	double field3;
} SCD_Struct_SB29;

typedef struct BKSDisplayBrightnessTransaction* BKSDisplayBrightnessTransactionRef;

typedef struct {
	unsigned long long field1;
	id field2;
	unsigned long long field3;
	unsigned long long field4[5];
} SCD_Struct_SB31;

typedef struct MGNotificationTokenStruct* MGNotificationTokenStructRef;

typedef struct {
	BOOL valid;
	SCD_Struct_SB20 styleTransitionState;
} SCD_Struct_SB33;

typedef struct {
	BOOL field1;
	SCD_Struct_SB20 field2;
} SCD_Struct_SB34;

typedef struct __CFRunLoopObserver* CFRunLoopObserverRef;

typedef struct __IOSurface* IOSurfaceRef;

typedef struct {
	int hour;
	int minute;
} SCD_Struct_SB37;

typedef struct {
	SCD_Struct_SB37 fromTime;
	SCD_Struct_SB37 toTime;
} SCD_Struct_SB38;

typedef struct {
	BOOL active;
	BOOL enabled;
	BOOL sunSchedulePermitted;
	int mode;
	SCD_Struct_SB38 schedule;
	unsigned long long disableFlags;
} SCD_Struct_SB39;

typedef struct {
	BOOL field1;
	BOOL field2;
	BOOL field3;
	int field4;
	SCD_Struct_SB38 field5;
	unsigned long long field6;
} SCD_Struct_SB40;

typedef struct SBNormalizedTransitionInterval {
	double start;
	double duration;
} SBNormalizedTransitionInterval;

typedef struct _CARenderImage* CARenderImageRef;

typedef struct {
	unsigned field1 : 1;
	unsigned field2 : 1;
	unsigned field3 : 1;
	unsigned field4 : 1;
	unsigned field5 : 1;
	unsigned field6 : 1;
	unsigned field7 : 1;
	unsigned field8 : 1;
	unsigned field9 : 1;
	unsigned field10 : 1;
	unsigned field11 : 1;
	unsigned field12 : 1;
} SCD_Struct_SB43;

typedef struct CGImage* CGImageRef;

typedef struct {
	BOOL itemIsEnabled[29];
	char timeString[64];
	int gsmSignalStrengthRaw;
	int gsmSignalStrengthBars;
	char serviceString[100];
	char serviceCrossfadeString[100];
	char serviceImages[2][100];
	char operatorDirectory[1024];
	unsigned serviceContentType;
	int wifiSignalStrengthRaw;
	int wifiSignalStrengthBars;
	unsigned dataNetworkType;
	int batteryCapacity;
	unsigned batteryState;
	char batteryDetailString[150];
	int bluetoothBatteryCapacity;
	int thermalColor;
	unsigned thermalSunlightMode : 1;
	unsigned slowActivity : 1;
	unsigned syncActivity : 1;
	char activityDisplayId[256];
	unsigned bluetoothConnected : 1;
	unsigned displayRawGSMSignal : 1;
	unsigned displayRawWifiSignal : 1;
	unsigned locationIconType : 1;
	unsigned quietModeInactive : 1;
	unsigned tetheringConnectionCount;
	unsigned batterySaverModeActive : 1;
	unsigned deviceIsRTL : 1;
	char breadcrumbTitle[256];
	char breadcrumbSecondaryTitle[256];
	char personName[100];
} SCD_Struct_SB45;

typedef struct OpaqueFigVirtualDisplaySession* OpaqueFigVirtualDisplaySessionRef;

typedef struct SBWindowLevelRange_struct {
	double start;
	double end;
} SBWindowLevelRange_struct;

typedef struct CGAffineTransform {
	double a;
	double b;
	double c;
	double d;
	double tx;
	double ty;
} CGAffineTransform;

typedef struct __CFArray* CFArrayRef;

