/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:32 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SPUISearchViewControllerPresentation <NSObject>
@property (assign,nonatomic) unsigned long long presentsFromEdge; 
@required
-(void)willBeginPresentingAnimated:(BOOL)arg1 fromSource:(unsigned long long)arg2;
-(void)willBeginPresentingAnimated:(BOOL)arg1;
-(void)updatePresentationProgress:(double)arg1;
-(void)didFinishPresenting:(BOOL)arg1;
-(void)willBeginDismissing:(BOOL)arg1;
-(unsigned long long)presentsFromEdge;
-(void)setPresentsFromEdge:(unsigned long long)arg1;

@end

