/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:28 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UIAlertViewDelegate <NSObject>
@optional
-(void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
-(void)alertViewCancel:(id)arg1;
-(void)willPresentAlertView:(id)arg1;
-(void)didPresentAlertView:(id)arg1;
-(void)alertView:(id)arg1 willDismissWithButtonIndex:(long long)arg2;
-(void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
-(BOOL)alertViewShouldEnableFirstOtherButton:(id)arg1;

@end

