/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, July 26, 2016 at 1:11:31 AM Pacific Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <SpringBoard/SpringBoard-Structs.h>
@interface UIGestureRecognizerTransformAnalyzerInfo : NSObject {

	double _translationMagnitude;
	double _scale;
	double _rotation;
	CGPoint _translation;
	CGPoint _absoluteTranslation;

}

@property (assign,nonatomic) CGPoint translation;                      //@synthesize translation=_translation - In the implementation block
@property (assign,nonatomic) double translationMagnitude;              //@synthesize translationMagnitude=_translationMagnitude - In the implementation block
@property (assign,nonatomic) CGPoint absoluteTranslation;              //@synthesize absoluteTranslation=_absoluteTranslation - In the implementation block
@property (assign,nonatomic) double scale;                             //@synthesize scale=_scale - In the implementation block
@property (assign,nonatomic) double rotation;                          //@synthesize rotation=_rotation - In the implementation block
-(void)_setTranslation:(CGPoint)arg1 ;
-(void)_setTranslationMagnitude:(double)arg1 ;
-(void)_setAbsoluteTranslation:(CGPoint)arg1 ;
-(void)_setRotation:(double)arg1 ;
-(double)translationMagnitude;
-(CGPoint)absoluteTranslation;
-(id)description;
-(void)_setScale:(double)arg1 ;
-(void)_reset;
-(double)scale;
-(double)rotation;
-(CGPoint)translation;
@end

